#!/usr/bin/env bash
#
# Bring up a disposable staging environment: a scratch PostgreSQL instance and
# a staging .env with placeholder credentials.
#
#   ./scripts/staging/setup-staging.sh            # scratch PG + placeholder tokens
#   ./scripts/staging/setup-staging.sh --keep-env # keep an existing .env untouched
#
# The database is a throwaway cluster under /tmp. Nothing here touches a
# production project, and the tokens written are structurally valid but fake —
# they let configuration validation pass so that everything up to the gateway
# handshake can be exercised. They cannot log in to Discord, by design.
#
# To connect to a real staging guild, replace the three DISCORD_*_TOKEN values
# with tokens from three *staging* Discord applications. .env is gitignored and
# must stay that way.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PGROOT="${BLOOM_STAGING_PGROOT:-/tmp/pg}"
PGDATA="${BLOOM_STAGING_PGDATA:-/tmp/pgdata}"
PGPORT="${BLOOM_STAGING_PGPORT:-55432}"
KEEP_ENV=0
[[ "${1:-}" == "--keep-env" ]] && KEEP_ENV=1

say() { printf '  %s\n' "$*"; }

printf '\nBloom staging environment\n\n'

# ---------------------------------------------------------------------------
# 1. A scratch PostgreSQL cluster.
# ---------------------------------------------------------------------------
PGBIN="$PGROOT/node_modules/@embedded-postgres/linux-x64/native/bin"

if [[ ! -x "$PGBIN/pg_ctl" ]]; then
  say "Installing an embedded PostgreSQL 17 into $PGROOT"
  mkdir -p "$PGROOT"
  (cd "$PGROOT" && npm i @embedded-postgres/linux-x64@17.4.0-beta.15 --silent >/dev/null 2>&1)
fi

if "$PGBIN/pg_ctl" -D "$PGDATA" status >/dev/null 2>&1; then
  say "PostgreSQL already running on port $PGPORT"
else
  if [[ ! -d "$PGDATA" ]]; then
    say "Initialising a scratch cluster at $PGDATA"
    printf 'postgres' > /tmp/bloom-pgpass
    "$PGBIN/initdb" -D "$PGDATA" -U postgres -A md5 --pwfile=/tmp/bloom-pgpass >/dev/null 2>&1
    rm -f /tmp/bloom-pgpass
  fi
  say "Starting PostgreSQL on port $PGPORT"
  "$PGBIN/pg_ctl" -D "$PGDATA" -o "-p $PGPORT -k /tmp" -l /tmp/bloom-pg.log start >/dev/null 2>&1
  sleep 2
fi

# ---------------------------------------------------------------------------
# 2. A staging .env.
#
# Placeholder tokens are three dot-separated base64url segments because that is
# the shape configuration validation enforces. They are deliberately distinct
# per bot: the loader rejects two bots sharing a token, which is a real
# safeguard against pointing all three processes at one application.
# ---------------------------------------------------------------------------
if [[ -f "$ROOT/.env" && $KEEP_ENV -eq 1 ]]; then
  say "Keeping the existing .env (--keep-env)"
else
  if [[ -f "$ROOT/.env" ]]; then
    cp "$ROOT/.env" "$ROOT/.env.backup.$(date +%s)"
    say "Backed up the existing .env"
  fi

  HDR='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9'
  write_env() {
    local bot=$1 body=$2 sig=$3 id=$4
    printf 'DISCORD_%s_TOKEN=%s.%s.%s\n' "$bot" "$HDR" "$body" "$sig"
    printf 'DISCORD_%s_CLIENT_ID=%s\n' "$bot" "$id"
  }

  {
    printf '# Generated by scripts/staging/setup-staging.sh — staging only.\n'
    printf '# Placeholder tokens: structurally valid, cannot authenticate.\n\n'
    write_env GUARDIAN  'eyJzdWIiOiIxMTExMTExMTExMTExMTExMTEiLCJpYXQiOjE1MTYyMzkwMjJ9' \
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' '111111111111111111'
    write_env COMPANION 'eyJzdWIiOiIyMjIyMjIyMjIyMjIyMjIyMjIiLCJpYXQiOjE1MTYyMzkwMjJ9' \
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb' '222222222222222222'
    write_env LABS      'eyJzdWIiOiIzMzMzMzMzMzMzMzMzMzMzMzMiLCJpYXQiOjE1MTYyMzkwMjJ9' \
      'ccccccccccccccccccccccccccccccccccccccccccc' '333333333333333333'
    printf '\nDISCORD_GUILD_ID=987654321098765432\n'

    # Role ids. Guardian refuses to start without all of these — correctly, since
    # guessing a role id means assigning the wrong role. Distinct fake snowflakes
    # here; replace with real ids from the staging guild before connecting.
    printf '\n'
    n=700000000000000001
    for role in FOUNDER ADMINISTRATOR MODERATOR BLOOM_BOT BETA_TESTER EARLY_BLOOM BLOOM_MEMBER; do
      printf 'ROLE_%s=%s\n' "$role" "$n"
      n=$((n + 1))
    done

    # Channel ids. Unset channels are a warning, not an error: a feature with no
    # destination refuses to post rather than guessing one.
    printf '\n'
    n=800000000000000001
    for ch in WELCOME RULES GETTING_STARTED ANNOUNCEMENTS RELEASE_NOTES \
              DEVELOPMENT_UPDATES INTRODUCTIONS DAILY_CHECK_IN SMALL_WINS \
              ACHIEVEMENTS MILESTONES BLOOM_REWARDS CHALLENGES BETA_TESTING \
              FEATURE_TESTING FEEDBACK FEATURE_REQUESTS VOTING FEATURE_STATUS \
              BUG_REPORTS SUPPORT MODERATION REPORTS INTERNAL; do
      printf 'CHANNEL_%s=%s\n' "$ch" "$n"
      n=$((n + 1))
    done
    printf '\nDATABASE_URL=postgres://postgres:postgres@127.0.0.1:%s/postgres\n' "$PGPORT"
    printf 'DATABASE_SCHEMA=bloom_discord\n'
    printf '\nNODE_ENV=development\n'
    printf 'BLOOM_ENVIRONMENT=development\n'
    printf 'LOG_LEVEL=info\n'
    printf 'LOG_PRETTY=false\n'
    printf 'BLOOM_VERSION=staging\n'
    printf '\nHEALTH_PORT_GUARDIAN=8080\n'
    printf 'HEALTH_PORT_COMPANION=8081\n'
    printf 'HEALTH_PORT_LABS=8082\n'
  } > "$ROOT/.env"

  say "Wrote $ROOT/.env with placeholder credentials"
fi

printf '\nNext:\n'
printf '  pnpm build && pnpm db:migrate && pnpm diagnostics\n'
printf '  ./scripts/staging/validate-staging.sh\n\n'
