-- ===========================================================================
-- Bloom — complete Supabase setup
--
-- Paste this whole file into your project's SQL editor and run it once.
-- Generated by scripts/make-sql.py — edit a migration, re-run the script.
--
-- It is safe to run on a project that already has some of these tables: every
-- statement is `create ... if not exists` / `create or replace` / `drop ... if
-- exists`, so re-running changes nothing that is already correct.
--
-- What this gives you:
--   • reward_items, reward_assignments, app_admins + the reward functions
--   • public.profiles — created only if your project doesn't have it yet
--   • identity columns, privacy, stories, highlights, the profile-media bucket
--   • cycle_entries — the cycle page
--   • tracker_days — the trackers page
--   • mood_entries — the mood page
--   • coach_messages, coach_memory — the coach's thread and facts

-- Then put these in .env.local and restart the dev server:
--
--   VITE_SUPABASE_URL=https://<your-project>.supabase.co
--   VITE_SUPABASE_ANON_KEY=<your anon key>
--
-- Full write-up: docs/SUPABASE-SETUP.md
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 20260826_reward_delivery.sql
-- reward_items, reward_assignments, app_admins + the reward functions
-- ---------------------------------------------------------------------------

-- Bloom reward delivery system
-- Run this migration in Supabase before using /admin/rewards.
-- Admin access is granted only by inserting a user id into app_admins from a
-- trusted SQL session. Never expose the service-role key in the browser.

create extension if not exists pgcrypto;

do $$ begin
  create type public.reward_state as enum ('draft', 'published', 'revoked', 'expired');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.reward_delivery_state as enum ('published', 'claimed', 'expired', 'revoked');
exception when duplicate_object then null;
end $$;

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.reward_items (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(trim(title)) between 1 and 120),
  description text not null default '',
  image_url text,
  reward_type text not null default 'recognition' check (char_length(trim(reward_type)) between 1 and 60),
  value_details text,
  admin_message text,
  state public.reward_state not null default 'draft',
  created_by uuid not null references auth.users(id) on delete restrict,
  publish_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reward_dates_are_valid check (expires_at is null or publish_at is null or expires_at > publish_at)
);

create table if not exists public.reward_assignments (
  reward_id uuid not null references public.reward_items(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  state public.reward_delivery_state not null default 'published',
  claimed_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (reward_id, user_id)
);

create index if not exists reward_items_state_publish_idx
  on public.reward_items (state, publish_at, expires_at);
create index if not exists reward_assignments_user_state_idx
  on public.reward_assignments (user_id, state, created_at desc);

create or replace function public.touch_reward_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists reward_items_touch_updated_at on public.reward_items;
create trigger reward_items_touch_updated_at
before update on public.reward_items
for each row execute function public.touch_reward_updated_at();

create or replace function public.is_rewards_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.app_admins
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_rewards_admin() from public;
grant execute on function public.is_rewards_admin() to authenticated;

alter table public.app_admins enable row level security;
alter table public.reward_items enable row level security;
alter table public.reward_assignments enable row level security;

revoke all on public.app_admins from anon, authenticated;
revoke all on public.reward_items from anon, authenticated;
revoke all on public.reward_assignments from anon, authenticated;

grant select on public.reward_items to authenticated;
grant select on public.reward_assignments to authenticated;

-- A user can only read an assignment addressed to their auth uid. The reward
-- itself must be published, within its publication window, and not expired.
-- Admins can inspect all rows through the security-definer admin functions.
drop policy if exists reward_items_user_read on public.reward_items;
create policy reward_items_user_read
on public.reward_items
for select
to authenticated
using (
  exists (
    select 1
    from public.reward_assignments assignment
    where assignment.reward_id = reward_items.id
      and assignment.user_id = auth.uid()
      and assignment.state in ('published', 'claimed')
      and reward_items.state = 'published'
      and (reward_items.publish_at is null or reward_items.publish_at <= now())
      and (
        reward_items.expires_at is null
        or reward_items.expires_at > now()
        or assignment.state = 'claimed'
      )
  )
  or public.is_rewards_admin()
);

drop policy if exists reward_assignments_user_read on public.reward_assignments;
create policy reward_assignments_user_read
on public.reward_assignments
for select
to authenticated
using (user_id = auth.uid() or public.is_rewards_admin());

-- User-facing query. It never accepts a user id from the browser; auth.uid()
-- is supplied by Supabase's signed JWT.
create or replace function public.get_my_rewards()
returns table (
  id uuid,
  title text,
  description text,
  image_url text,
  reward_type text,
  value_details text,
  admin_message text,
  publish_at timestamptz,
  expires_at timestamptz,
  delivery_state text,
  claimed_at timestamptz
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    item.id,
    item.title,
    item.description,
    item.image_url,
    item.reward_type,
    item.value_details,
    item.admin_message,
    item.publish_at,
    item.expires_at,
    assignment.state::text as delivery_state,
    assignment.claimed_at
  from public.reward_items item
  join public.reward_assignments assignment on assignment.reward_id = item.id
  where assignment.user_id = auth.uid()
    and assignment.state in ('published', 'claimed')
    and item.state = 'published'
    and (item.publish_at is null or item.publish_at <= now())
    and (
      item.expires_at is null
      or item.expires_at > now()
      or assignment.state = 'claimed'
    )
  order by coalesce(item.publish_at, item.created_at) desc;
$$;

grant execute on function public.get_my_rewards() to authenticated;

-- Claiming is the only user write path. A normal user cannot update an
-- assignment directly, publish an item, or choose another user's id.
create or replace function public.claim_reward(p_reward_id uuid)
returns table (
  id uuid,
  title text,
  delivery_state text,
  claimed_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  selected public.reward_items;
begin
  select item.* into selected
  from public.reward_items item
  join public.reward_assignments assignment on assignment.reward_id = item.id
  where item.id = p_reward_id
    and assignment.user_id = auth.uid()
    and assignment.state = 'published'
    and item.state = 'published'
    and (item.publish_at is null or item.publish_at <= now())
    and (item.expires_at is null or item.expires_at > now())
  for update of item;

  if not found then
    raise exception using
      errcode = '42501',
      message = 'This reward is not available to the current user.';
  end if;

  update public.reward_assignments assignment
  set state = 'claimed', claimed_at = now()
  where assignment.reward_id = p_reward_id
    and assignment.user_id = auth.uid()
    and assignment.state = 'published';

  return query
  select selected.id, selected.title, 'claimed'::text, now();
end;
$$;

grant execute on function public.claim_reward(uuid) to authenticated;

-- Admin-only user directory for recipient selection. It returns only the
-- fields needed by the admin form and cannot be called by normal users.
create or replace function public.admin_list_reward_users()
returns table (
  user_id uuid,
  email text,
  display_name text
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_rewards_admin() then
    raise exception using errcode = '42501', message = 'Rewards administrator access required.';
  end if;

  return query
  select
    users.id,
    users.email::text,
    coalesce(
      users.raw_user_meta_data ->> 'display_name',
      users.raw_user_meta_data ->> 'name',
      users.email
    )::text
  from auth.users users
  order by coalesce(users.raw_user_meta_data ->> 'display_name', users.email);
end;
$$;

grant execute on function public.admin_list_reward_users() to authenticated;

create or replace function public.admin_list_rewards()
returns table (
  id uuid,
  title text,
  description text,
  image_url text,
  reward_type text,
  value_details text,
  admin_message text,
  state text,
  publish_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz,
  recipient_ids uuid[],
  assignment_states jsonb
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_rewards_admin() then
    raise exception using errcode = '42501', message = 'Rewards administrator access required.';
  end if;

  return query
  select
    item.id,
    item.title,
    item.description,
    item.image_url,
    item.reward_type,
    item.value_details,
    item.admin_message,
    case
      when item.state = 'published' and item.expires_at is not null and item.expires_at <= now()
        then 'expired'
      else item.state::text
    end as state,
    item.publish_at,
    item.expires_at,
    item.created_at,
    coalesce(array_agg(assignment.user_id) filter (where assignment.user_id is not null), '{}'::uuid[]) as recipient_ids,
    coalesce(
      jsonb_agg(
        jsonb_build_object('user_id', assignment.user_id, 'state', assignment.state::text, 'claimed_at', assignment.claimed_at)
      ) filter (where assignment.user_id is not null),
      '[]'::jsonb
    ) as assignment_states
  from public.reward_items item
  left join public.reward_assignments assignment on assignment.reward_id = item.id
  group by item.id
  order by item.created_at desc;
end;
$$;

grant execute on function public.admin_list_rewards() to authenticated;

create or replace function public.admin_create_reward(
  p_title text,
  p_description text default '',
  p_image_url text default null,
  p_reward_type text default 'recognition',
  p_value_details text default null,
  p_admin_message text default null,
  p_publish_at timestamptz default null,
  p_expires_at timestamptz default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id uuid;
begin
  if not public.is_rewards_admin() then
    raise exception using errcode = '42501', message = 'Rewards administrator access required.';
  end if;

  if p_expires_at is not null and p_publish_at is not null and p_expires_at <= p_publish_at then
    raise exception using errcode = '22023', message = 'Expiration must be after publication.';
  end if;

  insert into public.reward_items (
    title, description, image_url, reward_type, value_details, admin_message,
    created_by, publish_at, expires_at, state
  ) values (
    trim(p_title), coalesce(p_description, ''), nullif(trim(p_image_url), ''),
    trim(p_reward_type), nullif(trim(p_value_details), ''), nullif(trim(p_admin_message), ''),
    auth.uid(), p_publish_at, p_expires_at, 'draft'
  ) returning id into new_id;

  return new_id;
end;
$$;

grant execute on function public.admin_create_reward(text, text, text, text, text, text, timestamptz, timestamptz) to authenticated;

create or replace function public.admin_update_reward(
  p_reward_id uuid,
  p_title text,
  p_description text default '',
  p_image_url text default null,
  p_reward_type text default 'recognition',
  p_value_details text default null,
  p_admin_message text default null,
  p_publish_at timestamptz default null,
  p_expires_at timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_rewards_admin() then
    raise exception using errcode = '42501', message = 'Rewards administrator access required.';
  end if;

  if p_expires_at is not null and p_publish_at is not null and p_expires_at <= p_publish_at then
    raise exception using errcode = '22023', message = 'Expiration must be after publication.';
  end if;

  update public.reward_items
  set title = trim(p_title),
      description = coalesce(p_description, ''),
      image_url = nullif(trim(p_image_url), ''),
      reward_type = trim(p_reward_type),
      value_details = nullif(trim(p_value_details), ''),
      admin_message = nullif(trim(p_admin_message), ''),
      publish_at = p_publish_at,
      expires_at = p_expires_at
  where id = p_reward_id;

  if not found then
    raise exception using errcode = '22023', message = 'Reward not found.';
  end if;
end;
$$;

grant execute on function public.admin_update_reward(uuid, text, text, text, text, text, text, timestamptz, timestamptz) to authenticated;

create or replace function public.admin_publish_reward(
  p_reward_id uuid,
  p_user_ids uuid[],
  p_publish_at timestamptz default now(),
  p_expires_at timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  reward_row public.reward_items;
  unknown_count integer;
begin
  if not public.is_rewards_admin() then
    raise exception using errcode = '42501', message = 'Rewards administrator access required.';
  end if;

  if coalesce(array_length(p_user_ids, 1), 0) = 0 then
    raise exception using errcode = '22023', message = 'Select at least one recipient before publishing.';
  end if;

  if p_expires_at is not null and p_expires_at <= p_publish_at then
    raise exception using errcode = '22023', message = 'Expiration must be after publication.';
  end if;

  select * into reward_row from public.reward_items where id = p_reward_id for update;
  if not found then
    raise exception using errcode = '22023', message = 'Reward not found.';
  end if;

  select count(*) into unknown_count
  from unnest(p_user_ids) selected_id
  where not exists (select 1 from auth.users users where users.id = selected_id);
  if unknown_count > 0 then
    raise exception using errcode = '22023', message = 'One or more recipients do not exist.';
  end if;

  update public.reward_items
  set state = 'published', publish_at = p_publish_at, expires_at = p_expires_at
  where id = p_reward_id;

  update public.reward_assignments assignment
  set state = case when assignment.state = 'claimed' then 'claimed' else 'revoked' end
  where assignment.reward_id = p_reward_id
    and not (assignment.user_id = any(p_user_ids));

  insert into public.reward_assignments (reward_id, user_id, state)
  select p_reward_id, selected_id, 'published'
  from (
    select distinct selected_id
    from unnest(p_user_ids) selected_id
  ) recipients
  on conflict (reward_id, user_id) do update
    set state = case when public.reward_assignments.state = 'claimed' then 'claimed' else 'published' end;
end;
$$;

grant execute on function public.admin_publish_reward(uuid, uuid[], timestamptz, timestamptz) to authenticated;

create or replace function public.admin_revoke_reward(p_reward_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_rewards_admin() then
    raise exception using errcode = '42501', message = 'Rewards administrator access required.';
  end if;

  update public.reward_items set state = 'revoked' where id = p_reward_id;
  if not found then
    raise exception using errcode = '22023', message = 'Reward not found.';
  end if;
  update public.reward_assignments set state = 'revoked'
  where reward_id = p_reward_id and state <> 'claimed';
end;
$$;

grant execute on function public.admin_revoke_reward(uuid) to authenticated;

create or replace function public.admin_set_reward_delivery_state(
  p_reward_id uuid,
  p_user_id uuid,
  p_state public.reward_delivery_state
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_rewards_admin() then
    raise exception using errcode = '42501', message = 'Rewards administrator access required.';
  end if;

  update public.reward_assignments
  set state = p_state,
      claimed_at = case when p_state = 'claimed' then coalesce(claimed_at, now()) else claimed_at end
  where reward_id = p_reward_id and user_id = p_user_id;

  if not found then
    raise exception using errcode = '22023', message = 'Reward recipient assignment not found.';
  end if;
end;
$$;

grant execute on function public.admin_set_reward_delivery_state(uuid, uuid, public.reward_delivery_state) to authenticated;

-- Optional owner setup, run manually after the migration with the intended
-- administrator's auth user id:
-- insert into public.app_admins (user_id) values ('YOUR-AUTH-USER-UUID');

-- Tighten function grants explicitly. Supabase/PostgreSQL functions may have
-- PUBLIC execute by default; only authenticated sessions need these RPCs.
revoke all on function public.touch_reward_updated_at() from public, anon, authenticated;
revoke all on function public.is_rewards_admin() from public, anon;
grant execute on function public.is_rewards_admin() to authenticated;
revoke all on function public.get_my_rewards() from public, anon;
grant execute on function public.get_my_rewards() to authenticated;
revoke all on function public.claim_reward(uuid) from public, anon;
grant execute on function public.claim_reward(uuid) to authenticated;
revoke all on function public.admin_list_reward_users() from public, anon;
grant execute on function public.admin_list_reward_users() to authenticated;
revoke all on function public.admin_list_rewards() from public, anon;
grant execute on function public.admin_list_rewards() to authenticated;
revoke all on function public.admin_create_reward(text, text, text, text, text, text, timestamptz, timestamptz) from public, anon;
grant execute on function public.admin_create_reward(text, text, text, text, text, text, timestamptz, timestamptz) to authenticated;
revoke all on function public.admin_update_reward(uuid, text, text, text, text, text, text, timestamptz, timestamptz) from public, anon;
grant execute on function public.admin_update_reward(uuid, text, text, text, text, text, text, timestamptz, timestamptz) to authenticated;
revoke all on function public.admin_publish_reward(uuid, uuid[], timestamptz, timestamptz) from public, anon;
grant execute on function public.admin_publish_reward(uuid, uuid[], timestamptz, timestamptz) to authenticated;
revoke all on function public.admin_revoke_reward(uuid) from public, anon;
grant execute on function public.admin_revoke_reward(uuid) to authenticated;
revoke all on function public.admin_set_reward_delivery_state(uuid, uuid, public.reward_delivery_state) from public, anon;
grant execute on function public.admin_set_reward_delivery_state(uuid, uuid, public.reward_delivery_state) to authenticated;


-- ---------------------------------------------------------------------------
-- 20260827_profiles_bootstrap.sql
-- public.profiles — created only if your project doesn't have it yet
-- ---------------------------------------------------------------------------

-- Bloom — the profiles row, if your project doesn't have one yet.
--
-- 20260828_profile_identity_stories.sql is additive: it ALTERs public.profiles
-- to add the identity columns (username, display_name, bio, avatar_path,
-- accent, featured). That only works if the table is already there. Most Bloom
-- projects created it months ago; this file creates it for the ones that didn't,
-- so the identity migration can't fail halfway through.
--
-- Safe to run on a project that already has the table — every statement here is
-- guarded with "if not exists".

create table if not exists public.profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  profile_name  text,
  total_points  integer not null default 0,
  created_at    timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- You read and edit your own row. Public reading goes through the
-- get_public_bloom_profile() function, which only returns what the privacy
-- settings allow — there is deliberately no anonymous SELECT policy here.
drop policy if exists "profiles bootstrap read own" on public.profiles;
create policy "profiles bootstrap read own" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "profiles bootstrap insert own" on public.profiles;
create policy "profiles bootstrap insert own" on public.profiles
  for insert with check (auth.uid() = id);

drop policy if exists "profiles bootstrap update own" on public.profiles;
create policy "profiles bootstrap update own" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);


-- ---------------------------------------------------------------------------
-- 20260828_profile_identity_stories.sql
-- identity columns, privacy, stories, highlights, the profile-media bucket
-- ---------------------------------------------------------------------------

-- Bloom — Profile 2.0: identity, privacy, stories, highlights.
-- Run this in the Supabase SQL editor after 20260826_reward_delivery.sql.
-- It is additive: existing `profiles` rows (id, profile_name, total_points)
-- keep working; new columns arrive with safe defaults so old clients are
-- unaffected. Privacy is enforced here (RLS), never in the browser.

-- ---------------------------------------------------------------------------
-- 1. Identity fields on the existing profiles row
-- ---------------------------------------------------------------------------
alter table public.profiles
  add column if not exists display_name text,
  add column if not exists username text,
  add column if not exists bio text,
  add column if not exists avatar_path text,
  add column if not exists accent text not null default 'violet',
  add column if not exists featured jsonb,
  add column if not exists updated_at timestamptz not null default now();

-- Legacy rows used profile_name; copy it into display_name once so nobody
-- loses the name they already had.
update public.profiles
   set display_name = nullif(trim(profile_name), '')
 where display_name is null and profile_name is not null;

create unique index if not exists profiles_username_key
  on public.profiles (lower(username))
 where username is not null;

do $$ begin
  alter table public.profiles
    add constraint profiles_username_shape
    check (username is null or (
      char_length(username) between 3 and 30
      and username ~ '^[a-z0-9_]+$'
    ));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.profiles
    add constraint profiles_display_name_length
    check (display_name is null or char_length(display_name) between 1 and 48);
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.profiles
    add constraint profiles_bio_length
    check (bio is null or char_length(bio) <= 200);
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.profiles
    add constraint profiles_accent_allowed
    check (accent in ('violet', 'sky', 'amber', 'sage', 'rose'));
exception when duplicate_object then null; end $$;

-- Keep the row for a signed-in user existing even for accounts created after
-- this migration (the legacy app only created rows on magic-link sign-in).
create or replace function public.handle_new_bloom_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, profile_name, display_name)
  values (new.id, 'Bloom User', null)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_bloom_profile();

-- ---------------------------------------------------------------------------
-- 2. Privacy (separate table — identity row stays identity)
-- ---------------------------------------------------------------------------
do $$ begin
  create type public.bloom_visibility as enum ('private', 'public');
exception when duplicate_object then null; end $$;

create table if not exists public.profile_privacy (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  profile_visibility public.bloom_visibility not null default 'private',
  story_visibility public.bloom_visibility not null default 'private',
  updated_at timestamptz not null default now()
);

alter table public.profile_privacy enable row level security;

drop policy if exists "owner reads own privacy" on public.profile_privacy;
create policy "owner reads own privacy" on public.profile_privacy
  for select using (profile_id = auth.uid());

drop policy if exists "owner writes own privacy" on public.profile_privacy;
create policy "owner writes own privacy" on public.profile_privacy
  for insert with check (profile_id = auth.uid());

drop policy if exists "owner updates own privacy" on public.profile_privacy;
create policy "owner updates own privacy" on public.profile_privacy
  for update using (profile_id = auth.uid());

-- ---------------------------------------------------------------------------
-- 3. Stories
-- ---------------------------------------------------------------------------
do $$ begin
  create type public.bloom_story_kind as enum
    ('text', 'photo', 'mood', 'reflection', 'win', 'reward', 'milestone');
exception when duplicate_object then null; end $$;

create table if not exists public.stories (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references auth.users(id) on delete cascade,
  kind public.bloom_story_kind not null default 'text',
  title text not null default '' check (char_length(title) <= 120),
  body text not null default '' check (char_length(body) <= 2000),
  media_path text,
  media_width integer,
  media_height integer,
  accent text not null default 'violet'
    check (accent in ('violet', 'sky', 'amber', 'sage', 'rose')),
  atmosphere text not null default 'quiet'
    check (atmosphere in ('quiet', 'field', 'ink')),
  source_kind text,
  source_id text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '24 hours',
  visibility public.bloom_visibility not null default 'private',
  deleted_at timestamptz,
  constraint stories_expire_after_creation check (expires_at > created_at)
);

create index if not exists stories_active_idx
  on public.stories (author_id, expires_at)
  where deleted_at is null;

alter table public.stories enable row level security;

-- Is profile public? Used by story policies so a private person's stories can
-- never leak even if their story rows say "public".
create or replace function public.is_profile_bloom_public(p_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profile_privacy pp
    where pp.profile_id = p_id
      and pp.profile_visibility = 'public'
  );
$$;

drop policy if exists "owner reads own stories" on public.stories;
create policy "owner reads own stories" on public.stories
  for select using (author_id = auth.uid());

drop policy if exists "visitors read public stories" on public.stories;
create policy "visitors read public stories" on public.stories
  for select using (
    deleted_at is null
    and visibility = 'public'
    and expires_at > now()
    and public.is_profile_bloom_public(author_id)
  );

drop policy if exists "owner creates stories" on public.stories;
create policy "owner creates stories" on public.stories
  for insert with check (author_id = auth.uid());

drop policy if exists "owner updates own stories" on public.stories;
create policy "owner updates own stories" on public.stories
  for update using (author_id = auth.uid());

drop policy if exists "owner deletes own stories" on public.stories;
create policy "owner deletes own stories" on public.stories
  for delete using (author_id = auth.uid());

-- ---------------------------------------------------------------------------
-- 4. Highlights — permanent, curated; private until the story is public
-- ---------------------------------------------------------------------------
create table if not exists public.story_highlights (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 40),
  accent text not null default 'violet'
    check (accent in ('violet', 'sky', 'amber', 'sage', 'rose')),
  icon text
    check (icon is null or icon in ('sparkle', 'trophy', 'journal', 'heart', 'plane', 'leaf', 'star')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.story_highlight_items (
  highlight_id uuid not null references public.story_highlights(id) on delete cascade,
  story_id uuid not null references public.stories(id) on delete cascade,
  position integer not null default 0,
  primary key (highlight_id, story_id)
);

create index if not exists story_highlight_items_story_idx
  on public.story_highlight_items (story_id);

alter table public.story_highlights enable row level security;
alter table public.story_highlight_items enable row level security;

drop policy if exists "owner reads own highlights" on public.story_highlights;
create policy "owner reads own highlights" on public.story_highlights
  for select using (owner_id = auth.uid());

drop policy if exists "visitors read public highlights" on public.story_highlights;
create policy "visitors read public highlights" on public.story_highlights
  for select using (public.is_profile_bloom_public(owner_id));

drop policy if exists "owner writes highlights" on public.story_highlights;
create policy "owner writes highlights" on public.story_highlights
  for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists "owner reads highlight items" on public.story_highlight_items;
create policy "owner reads highlight items" on public.story_highlight_items
  for select using (
    exists (
      select 1 from public.story_highlights sh
      where sh.id = highlight_id
        and (sh.owner_id = auth.uid() or public.is_profile_bloom_public(sh.owner_id))
    )
  );

drop policy if exists "owner writes highlight items" on public.story_highlight_items;
create policy "owner writes highlight items" on public.story_highlight_items
  for all using (
    exists (
      select 1 from public.story_highlights sh
      where sh.id = highlight_id and sh.owner_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.story_highlights sh
      where sh.id = highlight_id and sh.owner_id = auth.uid()
    )
  );

-- ---------------------------------------------------------------------------
-- 5. Identity reads
-- ---------------------------------------------------------------------------
-- Everyone may see the public identity columns (name/username are needed for
-- mentions); email/points are never exposed. Owner sees everything.
drop policy if exists "self reads own profile" on public.profiles;
create policy "self reads own profile" on public.profiles
  for select using (id = auth.uid());

drop policy if exists "owner updates own profile" on public.profiles;
create policy "owner updates own profile" on public.profiles
  for update using (id = auth.uid());

drop policy if exists "owner inserts own profile" on public.profiles;
create policy "owner inserts own profile" on public.profiles
  for insert with check (id = auth.uid());

-- Public profile card. Returns ONLY public fields, and only when the owner
-- chose public visibility. Never returns email, points, mood, coach, tracker.
create or replace function public.get_public_bloom_profile(p_username text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
  result jsonb;
begin
  select * into v_profile
  from public.profiles
  where username = lower(trim(p_username));

  if v_profile.id is null then
    return null;
  end if;

  if not public.is_profile_bloom_public(v_profile.id) then
    return jsonb_build_object('private', true, 'username', v_profile.username);
  end if;

  result := jsonb_build_object(
    'display_name', coalesce(nullif(trim(v_profile.display_name), ''), 'Bloom User'),
    'username', v_profile.username,
    'bio', nullif(trim(coalesce(v_profile.bio, '')), ''),
    'avatar_url', case
      when v_profile.avatar_path is null then null
      else 'profile-media/' || v_profile.avatar_path
    end,
    'accent', v_profile.accent,
    'featured', v_profile.featured,
    'stories', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', s.id,
        'kind', s.kind,
        'title', s.title,
        'body', s.body,
        'media_url', case when s.media_path is null then null
                          else 'profile-media/' || s.media_path end,
        'accent', s.accent,
        'created_at', s.created_at,
        'expires_at', s.expires_at
      ) order by s.created_at desc)
      from public.stories s
      where s.author_id = v_profile.id
        and s.deleted_at is null
        and s.visibility = 'public'
        and s.expires_at > now()
    ), '[]'::jsonb),
    'highlights', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', h.id,
        'name', h.name,
        'accent', h.accent,
        'stories', coalesce((
          select jsonb_agg(jsonb_build_object(
            'id', s.id,
            'kind', s.kind,
            'title', s.title,
            'body', s.body,
            'media_url', case when s.media_path is null then null
                              else 'profile-media/' || s.media_path end,
            'accent', s.accent,
            'created_at', s.created_at,
            'expires_at', s.expires_at
          ) order by i.position)
          from public.story_highlight_items i
          join public.stories s on s.id = i.story_id
          where i.highlight_id = h.id
            and s.deleted_at is null
            and s.visibility = 'public'
        ), '[]'::jsonb)
      ) order by h.created_at)
      from public.story_highlights h
      where h.owner_id = v_profile.id
    ), '[]'::jsonb)
  );

  return result;
end;
$$;

revoke all on function public.get_public_bloom_profile(text) from anon;
grant execute on function public.get_public_bloom_profile(text) to anon, authenticated;

-- Username availability without exposing the table (returns a boolean only).
create or replace function public.is_bloom_username_available(p_username text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select not exists (
    select 1 from public.profiles
    where username = lower(trim(p_username))
  );
$$;

grant execute on function public.is_bloom_username_available(text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 6. Media storage — one bucket, namespaced by user id
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('profile-media', 'profile-media', true)
on conflict (id) do nothing;

drop policy if exists "profile media public read" on storage.objects;
create policy "profile media public read" on storage.objects
  for select using (bucket_id = 'profile-media');

drop policy if exists "profile media owner writes" on storage.objects;
create policy "profile media owner writes" on storage.objects
  for insert with check (
    bucket_id = 'profile-media'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "profile media owner updates" on storage.objects;
create policy "profile media owner updates" on storage.objects
  for update using (
    bucket_id = 'profile-media'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "profile media owner deletes" on storage.objects;
create policy "profile media owner deletes" on storage.objects
  for delete using (
    bucket_id = 'profile-media'
    and (storage.foldername(name))[1] = auth.uid()::text
  );


-- ---------------------------------------------------------------------------
-- 20260829_cycle_intelligence.sql
-- cycle_entries — the cycle page
-- ---------------------------------------------------------------------------

-- Bloom — Cycle intelligence: schema hardening + owner-only enforcement.
-- Idempotent: safe on projects where the legacy page already created
-- `cycle_entries`, and it creates the table for fresh projects.
-- Privacy is enforced HERE, not in the browser: anon gets nothing at all,
-- every row is only ever visible/mutable by its owner, and there is no
-- cross-user path, no public view, and no public policy — cycle data never
-- reaches public profiles, stories, or share metadata (see the
-- get_public_bloom_profile function in the Profile migration, which selects
-- from other tables only).

create table if not exists public.cycle_entries (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  cycle_day integer,
  phase text check (phase is null or phase in ('menstrual','follicular','ovulation','luteal')),
  flow text check (flow is null or flow in ('none','spotting','light','medium','heavy')),
  temperature numeric check (temperature is null or (temperature >= 34 and temperature <= 40)),
  cervical_mucus text check (cervical_mucus is null or cervical_mucus in ('dry','sticky','creamy','watery','egg-white')),
  lh_test text check (lh_test is null or lh_test in ('negative','positive')),
  pain_level numeric check (pain_level is null or (pain_level >= 0 and pain_level <= 5)),
  sexual_activity text check (sexual_activity is null or sexual_activity in ('none','protected','unprotected')),
  contraceptive text check (contraceptive is null or contraceptive in ('none','pill','condom','iud','other')),
  energy numeric check (energy is null or (energy >= 1 and energy <= 5)),
  sleep_hours numeric check (sleep_hours is null or (sleep_hours >= 0 and sleep_hours <= 24)),
  mood text check (mood is null or mood in ('Low','Flat','Okay','Good','Energized')),
  symptoms text[] not null default '{}',
  notes text,
  next_period_in_days integer,
  logged_at timestamptz default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- additive columns for projects where the legacy table predates these fields
alter table public.cycle_entries add column if not exists temperature numeric;
alter table public.cycle_entries add column if not exists cervical_mucus text;
alter table public.cycle_entries add column if not exists lh_test text;
alter table public.cycle_entries add column if not exists pain_level numeric;
alter table public.cycle_entries add column if not exists sexual_activity text;
alter table public.cycle_entries add column if not exists contraceptive text;
alter table public.cycle_entries add column if not exists energy numeric;
alter table public.cycle_entries add column if not exists sleep_hours numeric;
alter table public.cycle_entries add column if not exists mood text;
alter table public.cycle_entries add column if not exists symptoms text[] not null default '{}';
alter table public.cycle_entries add column if not exists notes text;
alter table public.cycle_entries add column if not exists next_period_in_days integer;
alter table public.cycle_entries add column if not exists logged_at timestamptz default now();
alter table public.cycle_entries add column if not exists updated_at timestamptz default now();

create unique index if not exists cycle_entries_owner_day_key
  on public.cycle_entries (profile_id, date);
create index if not exists cycle_entries_owner_date_idx
  on public.cycle_entries (profile_id, date desc);

create or replace function public.touch_cycle_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists cycle_entries_touch_updated_at on public.cycle_entries;
create trigger cycle_entries_touch_updated_at
before update on public.cycle_entries
for each row execute function public.touch_cycle_updated_at();

-- ---------------------------------------------------------------------------
-- RLS: authenticated owner only. anon is granted nothing.
-- ---------------------------------------------------------------------------
alter table public.cycle_entries enable row level security;

drop policy if exists "cycle owner select" on public.cycle_entries;
create policy "cycle owner select" on public.cycle_entries
  for select using (profile_id = auth.uid());

drop policy if exists "cycle owner insert" on public.cycle_entries;
create policy "cycle owner insert" on public.cycle_entries
  for insert with check (profile_id = auth.uid());

drop policy if exists "cycle owner update" on public.cycle_entries;
create policy "cycle owner update" on public.cycle_entries
  for update using (profile_id = auth.uid()) with check (profile_id = auth.uid());

drop policy if exists "cycle owner delete" on public.cycle_entries;
create policy "cycle owner delete" on public.cycle_entries
  for delete using (profile_id = auth.uid());

revoke all on public.cycle_entries from anon;

-- No cycle data in public surfaces — assert the public profile function
-- never touched this table (it doesn't; documented here for reviewers):
--   public.get_public_bloom_profile() → profiles + stories + story_highlights only.


-- ---------------------------------------------------------------------------
-- 20260830120000_tracker_days.sql
-- tracker_days — the trackers page
-- ---------------------------------------------------------------------------

-- Bloom — daily trackers.
--
-- One row per person per day, holding sleep, water, study sessions, movement,
-- energy and screen time. Same shape as the app's DayEntry, same conflict key
-- the client upserts on: (profile_id, date).
--
-- Run this in the Supabase SQL editor (or `supabase db push`). Until it exists
-- the trackers page keeps working from the device and says so in the header.

create table if not exists public.tracker_days (
  id              uuid primary key default gen_random_uuid(),
  profile_id      uuid not null references auth.users (id) on delete cascade,
  date            date not null,

  sleep_minutes   smallint check (sleep_minutes is null or (sleep_minutes >= 0 and sleep_minutes <= 1080)),
  bed_time        text check (bed_time is null or bed_time ~ '^\d{1,2}:\d{2}$'),
  wake_time       text check (wake_time is null or wake_time ~ '^\d{1,2}:\d{2}$'),
  sleep_quality   smallint check (sleep_quality is null or (sleep_quality between 1 and 5)),

  water_ml        integer check (water_ml is null or (water_ml >= 0 and water_ml <= 8000)),
  sessions        jsonb not null default '[]'::jsonb,

  movement_minutes smallint check (movement_minutes is null or (movement_minutes >= 0 and movement_minutes <= 480)),
  energy          smallint check (energy is null or (energy between 1 and 5)),
  screen_minutes  smallint check (screen_minutes is null or (screen_minutes >= 0 and screen_minutes <= 1200)),

  notes           text,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  constraint tracker_days_profile_date unique (profile_id, date)
);

create index if not exists tracker_days_profile_date_idx
  on public.tracker_days (profile_id, date desc);

-- Keep updated_at honest; the client also sends it, and the trigger wins.
create or replace function public.touch_tracker_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists tracker_days_touch_updated_at on public.tracker_days;
create trigger tracker_days_touch_updated_at
before update on public.tracker_days
for each row execute function public.touch_tracker_updated_at();

-- ---------------------------------------------------------------------------
-- RLS: authenticated owner only. anon is granted nothing.
-- ---------------------------------------------------------------------------
alter table public.tracker_days enable row level security;

drop policy if exists "tracker owner select" on public.tracker_days;
create policy "tracker owner select" on public.tracker_days
  for select using (profile_id = auth.uid());

drop policy if exists "tracker owner insert" on public.tracker_days;
create policy "tracker owner insert" on public.tracker_days
  for insert with check (profile_id = auth.uid());

drop policy if exists "tracker owner update" on public.tracker_days;
create policy "tracker owner update" on public.tracker_days
  for update using (profile_id = auth.uid()) with check (profile_id = auth.uid());

drop policy if exists "tracker owner delete" on public.tracker_days;
create policy "tracker owner delete" on public.tracker_days
  for delete using (profile_id = auth.uid());


-- ---------------------------------------------------------------------------
-- 20260831000000_mood_entries.sql
-- mood_entries — the mood page
-- ---------------------------------------------------------------------------

-- Bloom — mood entries.
--
-- The mood page (/) has been writing to `mood_entries` for a while, but no
-- migration in this repo ever created it. On a project without it, saving a
-- mood throws and the page quietly falls back to the device: nothing is lost,
-- but nothing syncs either. This is the missing table.
--
-- One row per moment, not per day — you can log as often as you like, so there
-- is deliberately no unique key on (profile_id, date).

create table if not exists public.mood_entries (
  id              uuid primary key default gen_random_uuid(),
  profile_id      uuid not null references auth.users (id) on delete cascade,

  mood_label      text,
  -- 0–100: the client stores mood × 10 so older Bloom rows still read back
  mood_intensity  smallint check (mood_intensity is null or (mood_intensity between 0 and 100)),
  energy          smallint check (energy is null or (energy between 1 and 10)),
  stress          smallint check (stress is null or (stress between 1 and 10)),

  note            text,
  tags            text[] not null default '{}',

  logged_at       timestamptz not null default now(),
  date            date not null,
  created_at      timestamptz not null default now()
);

create index if not exists mood_entries_profile_logged_idx
  on public.mood_entries (profile_id, logged_at desc);

create index if not exists mood_entries_profile_date_idx
  on public.mood_entries (profile_id, date desc);

-- ---------------------------------------------------------------------------
-- RLS: authenticated owner only. anon is granted nothing.
-- ---------------------------------------------------------------------------
alter table public.mood_entries enable row level security;

drop policy if exists "mood owner select" on public.mood_entries;
create policy "mood owner select" on public.mood_entries
  for select using (profile_id = auth.uid());

drop policy if exists "mood owner insert" on public.mood_entries;
create policy "mood owner insert" on public.mood_entries
  for insert with check (profile_id = auth.uid());

drop policy if exists "mood owner update" on public.mood_entries;
create policy "mood owner update" on public.mood_entries
  for update using (profile_id = auth.uid()) with check (profile_id = auth.uid());

drop policy if exists "mood owner delete" on public.mood_entries;
create policy "mood owner delete" on public.mood_entries
  for delete using (profile_id = auth.uid());


-- ---------------------------------------------------------------------------
-- 20260831000100_coach_memory.sql
-- coach_messages, coach_memory — the coach's thread and facts
-- ---------------------------------------------------------------------------

-- Bloom — what the coach remembers.
--
-- /coach reads and writes `coach_messages` (the thread) and `coach_memory`
-- (the pinned facts it has learned). Neither table existed in this repo's
-- migrations, so on a fresh project the coach's history never left the device:
-- it worked, but you lost the thread the moment you changed browser.
--
-- The coach keeps its own device copy either way and degrades quietly, so this
-- migration is additive and nothing breaks if you run it later.

create table if not exists public.coach_messages (
  id          uuid primary key default gen_random_uuid(),
  profile_id  uuid not null references auth.users (id) on delete cascade,
  role        text not null check (role in ('user', 'coach')),
  content     text,
  sources     text[] not null default '{}',
  created_at  timestamptz not null default now()
);

create index if not exists coach_messages_profile_created_idx
  on public.coach_messages (profile_id, created_at desc);

create table if not exists public.coach_memory (
  id          uuid primary key default gen_random_uuid(),
  profile_id  uuid not null references auth.users (id) on delete cascade,
  category    text not null default 'context'
                check (category in ('pattern', 'preference', 'goal', 'context')),
  fact        text not null,
  pinned      boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists coach_memory_profile_updated_idx
  on public.coach_memory (profile_id, updated_at desc);

-- Unpinning a fact is an edit, so keep updated_at honest for the ordering.
create or replace function public.touch_coach_memory_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists coach_memory_touch_updated_at on public.coach_memory;
create trigger coach_memory_touch_updated_at
before update on public.coach_memory
for each row execute function public.touch_coach_memory_updated_at();

-- ---------------------------------------------------------------------------
-- RLS: authenticated owner only. anon is granted nothing.
-- ---------------------------------------------------------------------------
alter table public.coach_messages enable row level security;

drop policy if exists "coach messages owner select" on public.coach_messages;
create policy "coach messages owner select" on public.coach_messages
  for select using (profile_id = auth.uid());

drop policy if exists "coach messages owner insert" on public.coach_messages;
create policy "coach messages owner insert" on public.coach_messages
  for insert with check (profile_id = auth.uid());

drop policy if exists "coach messages owner delete" on public.coach_messages;
create policy "coach messages owner delete" on public.coach_messages
  for delete using (profile_id = auth.uid());

alter table public.coach_memory enable row level security;

drop policy if exists "coach memory owner select" on public.coach_memory;
create policy "coach memory owner select" on public.coach_memory
  for select using (profile_id = auth.uid());

drop policy if exists "coach memory owner insert" on public.coach_memory;
create policy "coach memory owner insert" on public.coach_memory
  for insert with check (profile_id = auth.uid());

drop policy if exists "coach memory owner update" on public.coach_memory;
create policy "coach memory owner update" on public.coach_memory
  for update using (profile_id = auth.uid()) with check (profile_id = auth.uid());

drop policy if exists "coach memory owner delete" on public.coach_memory;
create policy "coach memory owner delete" on public.coach_memory
  for delete using (profile_id = auth.uid());
