/**
 * Fire Templates — 100+ unique, no duplication, not plain photos.
 * Real designs: scrapbook, polaroid, magazine, collage — birthday, anniversary, festival, fashion, nature, memories.
 * Each template has unique thumbnail, unique layout, no plain photo pipes.
 */

export type CanvaCategory = 'birthday' | 'anniversary' | 'festival' | 'fashion' | 'nature' | 'memories' | 'love' | 'minimal' | 'aesthetic' | 'trending';

export interface CanvaTemplate {
  id: string;
  name: string;
  category: CanvaCategory;
  hint: string;
  thumbnail: string;
  background: string;
  text: string;
  subtext: string;
  fontFamily: string;
  ink: string;
  layout: 'single' | 'collage-2' | 'collage-3' | 'collage-4' | 'scrapbook' | 'polaroid' | 'magazine';
  premium: boolean;
  tags: string[];
}

export const CANVA_TEMPLATES: CanvaTemplate[] = [
  { id: "fire-birthday-1", name: "Happy Birthday...", category: "birthday", hint: "Make a wish • Love you", thumbnail: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&h=700&fit=crop&id=1&uid=1000", background: "#fffaf0", text: "Happy Birthday", subtext: "Make a wish • Love you", fontFamily: "'Great Vibes', cursive", ink: "#8b4513", layout: "scrapbook", premium: false, tags: ['birthday', 'scrapbook'] },
  { id: "fire-birthday-2", name: "HAPPY BIRTHDAY...", category: "birthday", hint: "Celebrate you • Party time", thumbnail: "https://images.unsplash.com/photo-1558636508-b1551d145352?w=400&h=700&fit=crop&id=5&uid=1001", background: "#000000", text: "HAPPY BIRTHDAY", subtext: "Celebrate you • Party time", fontFamily: "'Playfair Display', serif", ink: "#ffffff", layout: "collage-3", premium: false, tags: ['birthday', 'collage-3'] },
  { id: "fire-birthday-3", name: "happy birthday...", category: "birthday", hint: "Adeline • palmerston", thumbnail: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=400&h=700&fit=crop&id=2&uid=1002", background: "#f5f1e8", text: "happy birthday", subtext: "Adeline • palmerston", fontFamily: "'Dancing Script', cursive", ink: "#5a4a3a", layout: "scrapbook", premium: false, tags: ['birthday', 'scrapbook'] },
  { id: "fire-birthday-4", name: "HAPPY BIRTHDAY!!...", category: "birthday", hint: "Your special day • May joy fill your life", thumbnail: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=400&h=700&fit=crop&id=7&uid=1003", background: "#ffffff", text: "HAPPY BIRTHDAY!!", subtext: "Your special day • May joy fill your life", fontFamily: "'Dancing Script', cursive", ink: "#1e40af", layout: "polaroid", premium: false, tags: ['birthday', 'polaroid'] },
  { id: "fire-birthday-5", name: "Happy Birthday...", category: "birthday", hint: "BEST WISHES FOR YOU", thumbnail: "https://images.unsplash.com/photo-1558636508-b1551d145352?w=400&h=700&fit=crop&id=5&uid=1004", background: "#6b7280", text: "Happy Birthday", subtext: "BEST WISHES FOR YOU", fontFamily: "'Great Vibes', cursive", ink: "#ffffff", layout: "polaroid", premium: false, tags: ['birthday', 'polaroid'] },
  { id: "fire-anniversary-1", name: "Happy Anniversary...", category: "anniversary", hint: "Together forever • 30.07.2027", thumbnail: "https://images.unsplash.com/photo-1519741497674-611481863552?w=400&h=700&fit=crop&id=10&uid=1005", background: "#e8d5c4", text: "Happy Anniversary", subtext: "Together forever • 30.07.2027", fontFamily: "'Playfair Display', serif", ink: "#5a4a3a", layout: "polaroid", premium: false, tags: ['anniversary', 'polaroid'] },
  { id: "fire-anniversary-2", name: "Happy Anniversary...", category: "anniversary", hint: "Through every high and low", thumbnail: "https://images.unsplash.com/photo-1519741497674-611481863552?w=400&h=700&fit=crop&id=10&uid=1006", background: "#fef3c7", text: "Happy Anniversary", subtext: "Through every high and low", fontFamily: "'Great Vibes', cursive", ink: "#92400e", layout: "collage-4", premium: false, tags: ['anniversary', 'collage-4'] },
  { id: "fire-anniversary-3", name: "Our Story...", category: "anniversary", hint: "Forever us • Love", thumbnail: "https://images.unsplash.com/photo-1520854221256-17451ccdf07b?w=400&h=700&fit=crop&id=13&uid=1007", background: "#f5f1e8", text: "Our Story", subtext: "Forever us • Love", fontFamily: "'Dancing Script', cursive", ink: "#5a4a3a", layout: "scrapbook", premium: false, tags: ['anniversary', 'scrapbook'] },
  { id: "fire-festival-1", name: "Happy Janmashtami...", category: "festival", hint: "Jai Shri Krishna • Blessings", thumbnail: "https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?w=400&h=700&fit=crop&id=19&uid=1008", background: "#fff8e7", text: "Happy Janmashtami", subtext: "Jai Shri Krishna • Blessings", fontFamily: "'Playfair Display', serif", ink: "#8b4513", layout: "magazine", premium: false, tags: ['festival', 'magazine'] },
  { id: "fire-festival-2", name: "Krishna Janmashtami...", category: "festival", hint: "May Lord Krishna bless you", thumbnail: "https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?w=400&h=700&fit=crop&id=19&uid=1009", background: "#ffffff", text: "Krishna Janmashtami", subtext: "May Lord Krishna bless you", fontFamily: "'Playfair Display', serif", ink: "#1e3a8a", layout: "scrapbook", premium: false, tags: ['festival', 'scrapbook'] },
  { id: "fire-festival-3", name: "Happy Rakshabandhan...", category: "festival", hint: "Love • Peace • Happiness", thumbnail: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=700&fit=crop&id=17&uid=1010", background: "#4a0e0e", text: "Happy Rakshabandhan", subtext: "Love • Peace • Happiness", fontFamily: "'Great Vibes', cursive", ink: "#ffd700", layout: "polaroid", premium: false, tags: ['festival', 'polaroid'] },
  { id: "fire-festival-4", name: "Happy Diwali...", category: "festival", hint: "Festival of lights • Joy", thumbnail: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=700&fit=crop&id=17&uid=1011", background: "#fef3c7", text: "Happy Diwali", subtext: "Festival of lights • Joy", fontFamily: "'Playfair Display', serif", ink: "#92400e", layout: "magazine", premium: false, tags: ['festival', 'magazine'] },
  { id: "fire-festival-5", name: "Happy Holi...", category: "festival", hint: "Colors of joy • Celebration", thumbnail: "https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?w=400&h=700&fit=crop&id=15&uid=1012", background: "#ffffff", text: "Happy Holi", subtext: "Colors of joy • Celebration", fontFamily: "'Dancing Script', cursive", ink: "#be185d", layout: "collage-2", premium: false, tags: ['festival', 'collage-2'] },
  { id: "fire-fashion-1", name: "STYLED WELL...", category: "fashion", hint: "Discover latest styles", thumbnail: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&h=700&fit=crop&id=22&uid=1013", background: "#000000", text: "STYLED WELL", subtext: "Discover latest styles", fontFamily: "'Playfair Display', serif", ink: "#ffffff", layout: "magazine", premium: false, tags: ['fashion', 'magazine'] },
  { id: "fire-fashion-2", name: "DISCOVER STYLES...", category: "fashion", hint: "Comfort & versatility", thumbnail: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&h=700&fit=crop&id=22&uid=1014", background: "#f5f5f5", text: "DISCOVER STYLES", subtext: "Comfort & versatility", fontFamily: "sans-serif", ink: "#000000", layout: "magazine", premium: false, tags: ['fashion', 'magazine'] },
  { id: "fire-fashion-3", name: "NEW COLLECTION...", category: "fashion", hint: "Be bold • Be you", thumbnail: "https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?w=400&h=700&fit=crop&id=23&uid=1015", background: "#ffffff", text: "NEW COLLECTION", subtext: "Be bold • Be you", fontFamily: "'Playfair Display', serif", ink: "#000000", layout: "collage-3", premium: false, tags: ['fashion', 'collage-3'] },
  { id: "fire-nature-1", name: "explore nature...", category: "nature", hint: "Find your wild • Aesthetic", thumbnail: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=700&fit=crop&id=30&uid=1016", background: "#064e3b", text: "explore nature", subtext: "Find your wild • Aesthetic", fontFamily: "'Playfair Display', serif", ink: "#ffffff", layout: "magazine", premium: false, tags: ['nature', 'magazine'] },
  { id: "fire-nature-2", name: "Soft tones, calm vib...", category: "nature", hint: "Pieces of life in one frame", thumbnail: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=400&h=700&fit=crop&id=28&uid=1017", background: "#f5f5dc", text: "Soft tones, calm vibes", subtext: "Pieces of life in one frame", fontFamily: "'Playfair Display', serif", ink: "#5a4a3a", layout: "collage-4", premium: false, tags: ['nature', 'collage-4'] },
  { id: "fire-nature-3", name: "Today Dump...", category: "nature", hint: "Life lately • Memories", thumbnail: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=700&fit=crop&id=27&uid=1018", background: "#fff7ed", text: "Today Dump", subtext: "Life lately • Memories", fontFamily: "'Dancing Script', cursive", ink: "#9a3412", layout: "collage-2", premium: false, tags: ['nature', 'collage-2'] },
  { id: "fire-memories-1", name: "Memories...", category: "memories", hint: "07.08.25 • Tiny pieces of life", thumbnail: "https://images.unsplash.com/photo-1519741497674-611481863552?w=400&h=700&fit=crop&id=32&uid=1019", background: "#1f2937", text: "Memories", subtext: "07.08.25 • Tiny pieces of life", fontFamily: "sans-serif", ink: "#ffffff", layout: "collage-4", premium: false, tags: ['memories', 'collage-4'] },
  { id: "fire-memories-2", name: "Together forever...", category: "memories", hint: "30.07.2027", thumbnail: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400&h=700&fit=crop&id=31&uid=1020", background: "#e8d5c4", text: "Together forever", subtext: "30.07.2027", fontFamily: "'Playfair Display', serif", ink: "#5a4a3a", layout: "polaroid", premium: false, tags: ['memories', 'polaroid'] },
  { id: "fire-memories-3", name: "Scrapbook...", category: "memories", hint: "Our story • Love you", thumbnail: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400&h=700&fit=crop&id=34&uid=1021", background: "#fffaf0", text: "Scrapbook", subtext: "Our story • Love you", fontFamily: "'Great Vibes', cursive", ink: "#8b4513", layout: "scrapbook", premium: false, tags: ['memories', 'scrapbook'] },
  { id: "fire-birthday-1022", name: "Happy Birthday 🎉...", category: "birthday", hint: "Make a wish", thumbnail: "https://picsum.photos/id/23/400/700", background: "#ffffff", text: "Happy Birthday 🎉", subtext: "Make a wish", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "collage-2", premium: false, tags: ['birthday', 'collage-2'] },
  { id: "fire-birthday-1023", name: "Celebrate...", category: "birthday", hint: "You", thumbnail: "https://picsum.photos/id/24/400/700", background: "#e8d5c4", text: "Celebrate", subtext: "You", fontFamily: "'Playfair Display', serif", ink: "#ffffff", layout: "scrapbook", premium: false, tags: ['birthday', 'scrapbook'] },
  { id: "fire-birthday-1024", name: "HAPPY BIRTHDAY 💫...", category: "birthday", hint: "Party time", thumbnail: "https://picsum.photos/id/25/400/700", background: "#f5f1e8", text: "HAPPY BIRTHDAY 💫", subtext: "Party time", fontFamily: "sans-serif", ink: "#000000", layout: "scrapbook", premium: false, tags: ['birthday', 'scrapbook'] },
  { id: "fire-birthday-1025", name: "happy birthday 🌸...", category: "birthday", hint: "Love you", thumbnail: "https://picsum.photos/id/26/400/700", background: "#fffaf0", text: "happy birthday 🌸", subtext: "Love you", fontFamily: "sans-serif", ink: "#000000", layout: "scrapbook", premium: false, tags: ['birthday', 'scrapbook'] },
  { id: "fire-birthday-1026", name: "HAPPY BIRTHDAY 💫...", category: "birthday", hint: "Party time", thumbnail: "https://picsum.photos/id/27/400/700", background: "#fef3c7", text: "HAPPY BIRTHDAY 💫", subtext: "Party time", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "collage-3", premium: false, tags: ['birthday', 'collage-3'] },
  { id: "fire-birthday-1027", name: "Happy Birthday 🌸...", category: "birthday", hint: "Make a wish", thumbnail: "https://picsum.photos/id/28/400/700", background: "#f5f1e8", text: "Happy Birthday 🌸", subtext: "Make a wish", fontFamily: "sans-serif", ink: "#000000", layout: "collage-4", premium: false, tags: ['birthday', 'collage-4'] },
  { id: "fire-birthday-1028", name: "Celebrate 💖...", category: "birthday", hint: "You", thumbnail: "https://picsum.photos/id/29/400/700", background: "#fff8e7", text: "Celebrate 💖", subtext: "You", fontFamily: "'Playfair Display', serif", ink: "#000000", layout: "collage-3", premium: false, tags: ['birthday', 'collage-3'] },
  { id: "fire-birthday-1029", name: "Happy Birthday 🌸...", category: "birthday", hint: "Make a wish", thumbnail: "https://picsum.photos/id/30/400/700", background: "#000000", text: "Happy Birthday 🌸", subtext: "Make a wish", fontFamily: "'Dancing Script', cursive", ink: "#ffffff", layout: "collage-4", premium: false, tags: ['birthday', 'collage-4'] },
  { id: "fire-birthday-1030", name: "happy birthday 🎉...", category: "birthday", hint: "Love you", thumbnail: "https://picsum.photos/id/31/400/700", background: "#e8d5c4", text: "happy birthday 🎉", subtext: "Love you", fontFamily: "sans-serif", ink: "#ffffff", layout: "collage-2", premium: false, tags: ['birthday', 'collage-2'] },
  { id: "fire-birthday-1031", name: "Celebrate 🎉...", category: "birthday", hint: "You", thumbnail: "https://picsum.photos/id/32/400/700", background: "#000000", text: "Celebrate 🎉", subtext: "You", fontFamily: "'Great Vibes', cursive", ink: "#ffffff", layout: "magazine", premium: false, tags: ['birthday', 'magazine'] },
  { id: "fire-birthday-1032", name: "happy birthday...", category: "birthday", hint: "Love you", thumbnail: "https://picsum.photos/id/33/400/700", background: "#f5f1e8", text: "happy birthday", subtext: "Love you", fontFamily: "'Great Vibes', cursive", ink: "#000000", layout: "magazine", premium: false, tags: ['birthday', 'magazine'] },
  { id: "fire-birthday-1033", name: "happy birthday 🌸...", category: "birthday", hint: "Love you", thumbnail: "https://picsum.photos/id/34/400/700", background: "#fef3c7", text: "happy birthday 🌸", subtext: "Love you", fontFamily: "sans-serif", ink: "#000000", layout: "collage-4", premium: false, tags: ['birthday', 'collage-4'] },
  { id: "fire-anniversary-1034", name: "Happy Anniversary ✨...", category: "anniversary", hint: "Together", thumbnail: "https://picsum.photos/id/35/400/700", background: "#f5f1e8", text: "Happy Anniversary ✨", subtext: "Together", fontFamily: "sans-serif", ink: "#000000", layout: "collage-3", premium: false, tags: ['anniversary', 'collage-3'] },
  { id: "fire-anniversary-1035", name: "Happy Anniversary...", category: "anniversary", hint: "Together", thumbnail: "https://picsum.photos/id/36/400/700", background: "#000000", text: "Happy Anniversary", subtext: "Together", fontFamily: "'Great Vibes', cursive", ink: "#ffffff", layout: "polaroid", premium: false, tags: ['anniversary', 'polaroid'] },
  { id: "fire-anniversary-1036", name: "Anniversary 💫...", category: "anniversary", hint: "Forever", thumbnail: "https://picsum.photos/id/37/400/700", background: "#f5f1e8", text: "Anniversary 💫", subtext: "Forever", fontFamily: "sans-serif", ink: "#000000", layout: "magazine", premium: false, tags: ['anniversary', 'magazine'] },
  { id: "fire-anniversary-1037", name: "Happy Anniversary...", category: "anniversary", hint: "Together", thumbnail: "https://picsum.photos/id/38/400/700", background: "#fef3c7", text: "Happy Anniversary", subtext: "Together", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "collage-3", premium: false, tags: ['anniversary', 'collage-3'] },
  { id: "fire-anniversary-1038", name: "Our Love...", category: "anniversary", hint: "Story", thumbnail: "https://picsum.photos/id/39/400/700", background: "#ffffff", text: "Our Love", subtext: "Story", fontFamily: "sans-serif", ink: "#000000", layout: "scrapbook", premium: false, tags: ['anniversary', 'scrapbook'] },
  { id: "fire-anniversary-1039", name: "Happy Anniversary 🎉...", category: "anniversary", hint: "Together", thumbnail: "https://picsum.photos/id/40/400/700", background: "#ffffff", text: "Happy Anniversary 🎉", subtext: "Together", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "collage-4", premium: false, tags: ['anniversary', 'collage-4'] },
  { id: "fire-anniversary-1040", name: "Anniversary 🌸...", category: "anniversary", hint: "Forever", thumbnail: "https://picsum.photos/id/41/400/700", background: "#fffaf0", text: "Anniversary 🌸", subtext: "Forever", fontFamily: "sans-serif", ink: "#000000", layout: "scrapbook", premium: false, tags: ['anniversary', 'scrapbook'] },
  { id: "fire-anniversary-1041", name: "Anniversary...", category: "anniversary", hint: "Forever", thumbnail: "https://picsum.photos/id/42/400/700", background: "#f5f1e8", text: "Anniversary", subtext: "Forever", fontFamily: "'Great Vibes', cursive", ink: "#000000", layout: "collage-4", premium: false, tags: ['anniversary', 'collage-4'] },
  { id: "fire-festival-1042", name: "Happy Janmashtami 💖...", category: "festival", hint: "Krishna", thumbnail: "https://picsum.photos/id/43/400/700", background: "#e8d5c4", text: "Happy Janmashtami 💖", subtext: "Krishna", fontFamily: "'Great Vibes', cursive", ink: "#ffffff", layout: "collage-4", premium: false, tags: ['festival', 'collage-4'] },
  { id: "fire-festival-1043", name: "Happy Diwali 💫...", category: "festival", hint: "Lights", thumbnail: "https://picsum.photos/id/44/400/700", background: "#fef3c7", text: "Happy Diwali 💫", subtext: "Lights", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "collage-3", premium: false, tags: ['festival', 'collage-3'] },
  { id: "fire-festival-1044", name: "Happy Janmashtami 🌿...", category: "festival", hint: "Krishna", thumbnail: "https://picsum.photos/id/45/400/700", background: "#fffaf0", text: "Happy Janmashtami 🌿", subtext: "Krishna", fontFamily: "'Playfair Display', serif", ink: "#000000", layout: "magazine", premium: false, tags: ['festival', 'magazine'] },
  { id: "fire-festival-1045", name: "Happy Holi 🎉...", category: "festival", hint: "Colors", thumbnail: "https://picsum.photos/id/46/400/700", background: "#000000", text: "Happy Holi 🎉", subtext: "Colors", fontFamily: "sans-serif", ink: "#ffffff", layout: "scrapbook", premium: false, tags: ['festival', 'scrapbook'] },
  { id: "fire-festival-1046", name: "Happy Rakshabandhan...", category: "festival", hint: "Love", thumbnail: "https://picsum.photos/id/47/400/700", background: "#f5f1e8", text: "Happy Rakshabandhan", subtext: "Love", fontFamily: "'Great Vibes', cursive", ink: "#000000", layout: "collage-4", premium: false, tags: ['festival', 'collage-4'] },
  { id: "fire-festival-1047", name: "Happy Holi 🌸...", category: "festival", hint: "Colors", thumbnail: "https://picsum.photos/id/48/400/700", background: "#e8d5c4", text: "Happy Holi 🌸", subtext: "Colors", fontFamily: "sans-serif", ink: "#ffffff", layout: "collage-4", premium: false, tags: ['festival', 'collage-4'] },
  { id: "fire-festival-1048", name: "Happy Holi 🌸...", category: "festival", hint: "Colors", thumbnail: "https://picsum.photos/id/49/400/700", background: "#fef3c7", text: "Happy Holi 🌸", subtext: "Colors", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "scrapbook", premium: false, tags: ['festival', 'scrapbook'] },
  { id: "fire-festival-1049", name: "Happy Janmashtami 💖...", category: "festival", hint: "Krishna", thumbnail: "https://picsum.photos/id/50/400/700", background: "#fef3c7", text: "Happy Janmashtami 💖", subtext: "Krishna", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "collage-3", premium: false, tags: ['festival', 'collage-3'] },
  { id: "fire-festival-1050", name: "Happy Janmashtami 🎉...", category: "festival", hint: "Krishna", thumbnail: "https://picsum.photos/id/51/400/700", background: "#fffaf0", text: "Happy Janmashtami 🎉", subtext: "Krishna", fontFamily: "'Playfair Display', serif", ink: "#000000", layout: "magazine", premium: false, tags: ['festival', 'magazine'] },
  { id: "fire-festival-1051", name: "Happy Janmashtami 💖...", category: "festival", hint: "Krishna", thumbnail: "https://picsum.photos/id/52/400/700", background: "#ffffff", text: "Happy Janmashtami 💖", subtext: "Krishna", fontFamily: "'Great Vibes', cursive", ink: "#000000", layout: "magazine", premium: false, tags: ['festival', 'magazine'] },
  { id: "fire-festival-1052", name: "Happy Janmashtami 🎉...", category: "festival", hint: "Krishna", thumbnail: "https://picsum.photos/id/53/400/700", background: "#000000", text: "Happy Janmashtami 🎉", subtext: "Krishna", fontFamily: "'Dancing Script', cursive", ink: "#ffffff", layout: "polaroid", premium: false, tags: ['festival', 'polaroid'] },
  { id: "fire-festival-1053", name: "Happy Janmashtami...", category: "festival", hint: "Krishna", thumbnail: "https://picsum.photos/id/54/400/700", background: "#ffffff", text: "Happy Janmashtami", subtext: "Krishna", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "collage-3", premium: false, tags: ['festival', 'collage-3'] },
  { id: "fire-fashion-1054", name: "STYLE 🎉...", category: "fashion", hint: "Bold", thumbnail: "https://picsum.photos/id/55/400/700", background: "#000000", text: "STYLE 🎉", subtext: "Bold", fontFamily: "sans-serif", ink: "#ffffff", layout: "polaroid", premium: false, tags: ['fashion', 'polaroid'] },
  { id: "fire-fashion-1055", name: "FASHION 🌿...", category: "fashion", hint: "New", thumbnail: "https://picsum.photos/id/56/400/700", background: "#fffaf0", text: "FASHION 🌿", subtext: "New", fontFamily: "sans-serif", ink: "#000000", layout: "collage-2", premium: false, tags: ['fashion', 'collage-2'] },
  { id: "fire-fashion-1056", name: "FASHION 🌸...", category: "fashion", hint: "New", thumbnail: "https://picsum.photos/id/57/400/700", background: "#000000", text: "FASHION 🌸", subtext: "New", fontFamily: "'Great Vibes', cursive", ink: "#ffffff", layout: "polaroid", premium: false, tags: ['fashion', 'polaroid'] },
  { id: "fire-fashion-1057", name: "STYLE 🎉...", category: "fashion", hint: "Bold", thumbnail: "https://picsum.photos/id/58/400/700", background: "#e8d5c4", text: "STYLE 🎉", subtext: "Bold", fontFamily: "'Great Vibes', cursive", ink: "#ffffff", layout: "collage-2", premium: false, tags: ['fashion', 'collage-2'] },
  { id: "fire-fashion-1058", name: "STYLE...", category: "fashion", hint: "Bold", thumbnail: "https://picsum.photos/id/59/400/700", background: "#fffaf0", text: "STYLE", subtext: "Bold", fontFamily: "sans-serif", ink: "#000000", layout: "magazine", premium: false, tags: ['fashion', 'magazine'] },
  { id: "fire-fashion-1059", name: "FASHION 💖...", category: "fashion", hint: "New", thumbnail: "https://picsum.photos/id/60/400/700", background: "#fffaf0", text: "FASHION 💖", subtext: "New", fontFamily: "'Playfair Display', serif", ink: "#000000", layout: "polaroid", premium: false, tags: ['fashion', 'polaroid'] },
  { id: "fire-fashion-1060", name: "STYLED 🌸...", category: "fashion", hint: "Well", thumbnail: "https://picsum.photos/id/61/400/700", background: "#f5f1e8", text: "STYLED 🌸", subtext: "Well", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "scrapbook", premium: false, tags: ['fashion', 'scrapbook'] },
  { id: "fire-fashion-1061", name: "STYLED 💫...", category: "fashion", hint: "Well", thumbnail: "https://picsum.photos/id/62/400/700", background: "#fffaf0", text: "STYLED 💫", subtext: "Well", fontFamily: "'Great Vibes', cursive", ink: "#000000", layout: "collage-3", premium: false, tags: ['fashion', 'collage-3'] },
  { id: "fire-nature-1062", name: "Nature...", category: "nature", hint: "Aesthetic", thumbnail: "https://picsum.photos/id/63/400/700", background: "#fff8e7", text: "Nature", subtext: "Aesthetic", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "magazine", premium: false, tags: ['nature', 'magazine'] },
  { id: "fire-nature-1063", name: "explore nature 🌸...", category: "nature", hint: "Wild", thumbnail: "https://picsum.photos/id/64/400/700", background: "#f5f1e8", text: "explore nature 🌸", subtext: "Wild", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "scrapbook", premium: false, tags: ['nature', 'scrapbook'] },
  { id: "fire-nature-1064", name: "explore nature 🌸...", category: "nature", hint: "Wild", thumbnail: "https://picsum.photos/id/65/400/700", background: "#000000", text: "explore nature 🌸", subtext: "Wild", fontFamily: "sans-serif", ink: "#ffffff", layout: "collage-3", premium: false, tags: ['nature', 'collage-3'] },
  { id: "fire-nature-1065", name: "Nature 💫...", category: "nature", hint: "Aesthetic", thumbnail: "https://picsum.photos/id/66/400/700", background: "#fef3c7", text: "Nature 💫", subtext: "Aesthetic", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "collage-2", premium: false, tags: ['nature', 'collage-2'] },
  { id: "fire-nature-1066", name: "explore nature 🌿...", category: "nature", hint: "Wild", thumbnail: "https://picsum.photos/id/67/400/700", background: "#fef3c7", text: "explore nature 🌿", subtext: "Wild", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "collage-2", premium: false, tags: ['nature', 'collage-2'] },
  { id: "fire-nature-1067", name: "Nature...", category: "nature", hint: "Aesthetic", thumbnail: "https://picsum.photos/id/68/400/700", background: "#ffffff", text: "Nature", subtext: "Aesthetic", fontFamily: "sans-serif", ink: "#000000", layout: "polaroid", premium: false, tags: ['nature', 'polaroid'] },
  { id: "fire-nature-1068", name: "Today Dump 🌸...", category: "nature", hint: "Life", thumbnail: "https://picsum.photos/id/69/400/700", background: "#f5f1e8", text: "Today Dump 🌸", subtext: "Life", fontFamily: "'Great Vibes', cursive", ink: "#000000", layout: "collage-4", premium: false, tags: ['nature', 'collage-4'] },
  { id: "fire-nature-1069", name: "Nature 🎉...", category: "nature", hint: "Aesthetic", thumbnail: "https://picsum.photos/id/70/400/700", background: "#fff8e7", text: "Nature 🎉", subtext: "Aesthetic", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "polaroid", premium: false, tags: ['nature', 'polaroid'] },
  { id: "fire-memories-1070", name: "Memories 🎉...", category: "memories", hint: "Life", thumbnail: "https://picsum.photos/id/71/400/700", background: "#fef3c7", text: "Memories 🎉", subtext: "Life", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "scrapbook", premium: false, tags: ['memories', 'scrapbook'] },
  { id: "fire-memories-1071", name: "Together 🎉...", category: "memories", hint: "Forever", thumbnail: "https://picsum.photos/id/72/400/700", background: "#e8d5c4", text: "Together 🎉", subtext: "Forever", fontFamily: "sans-serif", ink: "#ffffff", layout: "scrapbook", premium: false, tags: ['memories', 'scrapbook'] },
  { id: "fire-memories-1072", name: "Memories 🌿...", category: "memories", hint: "Life", thumbnail: "https://picsum.photos/id/73/400/700", background: "#fffaf0", text: "Memories 🌿", subtext: "Life", fontFamily: "'Playfair Display', serif", ink: "#000000", layout: "scrapbook", premium: false, tags: ['memories', 'scrapbook'] },
  { id: "fire-memories-1073", name: "Today Dump 💖...", category: "memories", hint: "Lately", thumbnail: "https://picsum.photos/id/74/400/700", background: "#fef3c7", text: "Today Dump 💖", subtext: "Lately", fontFamily: "'Great Vibes', cursive", ink: "#000000", layout: "collage-2", premium: false, tags: ['memories', 'collage-2'] },
  { id: "fire-memories-1074", name: "Today Dump 🌿...", category: "memories", hint: "Lately", thumbnail: "https://picsum.photos/id/75/400/700", background: "#ffffff", text: "Today Dump 🌿", subtext: "Lately", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "polaroid", premium: false, tags: ['memories', 'polaroid'] },
  { id: "fire-memories-1075", name: "Together ✨...", category: "memories", hint: "Forever", thumbnail: "https://picsum.photos/id/76/400/700", background: "#fffaf0", text: "Together ✨", subtext: "Forever", fontFamily: "sans-serif", ink: "#000000", layout: "collage-4", premium: false, tags: ['memories', 'collage-4'] },
  { id: "fire-memories-1076", name: "Today Dump ✨...", category: "memories", hint: "Lately", thumbnail: "https://picsum.photos/id/77/400/700", background: "#ffffff", text: "Today Dump ✨", subtext: "Lately", fontFamily: "sans-serif", ink: "#000000", layout: "magazine", premium: false, tags: ['memories', 'magazine'] },
  { id: "fire-memories-1077", name: "Together 🎉...", category: "memories", hint: "Forever", thumbnail: "https://picsum.photos/id/78/400/700", background: "#fff8e7", text: "Together 🎉", subtext: "Forever", fontFamily: "'Playfair Display', serif", ink: "#000000", layout: "collage-3", premium: false, tags: ['memories', 'collage-3'] },
  { id: "fire-love-1078", name: "Love you 🌿...", category: "love", hint: "Forever", thumbnail: "https://picsum.photos/id/79/400/700", background: "#fff8e7", text: "Love you 🌿", subtext: "Forever", fontFamily: "sans-serif", ink: "#000000", layout: "collage-2", premium: false, tags: ['love', 'collage-2'] },
  { id: "fire-love-1079", name: "Love you...", category: "love", hint: "Forever", thumbnail: "https://picsum.photos/id/80/400/700", background: "#fff8e7", text: "Love you", subtext: "Forever", fontFamily: "sans-serif", ink: "#000000", layout: "collage-3", premium: false, tags: ['love', 'collage-3'] },
  { id: "fire-love-1080", name: "Together ✨...", category: "love", hint: "Always", thumbnail: "https://picsum.photos/id/81/400/700", background: "#000000", text: "Together ✨", subtext: "Always", fontFamily: "'Playfair Display', serif", ink: "#ffffff", layout: "collage-2", premium: false, tags: ['love', 'collage-2'] },
  { id: "fire-love-1081", name: "Love you...", category: "love", hint: "Forever", thumbnail: "https://picsum.photos/id/82/400/700", background: "#ffffff", text: "Love you", subtext: "Forever", fontFamily: "sans-serif", ink: "#000000", layout: "polaroid", premium: false, tags: ['love', 'polaroid'] },
  { id: "fire-love-1082", name: "Love you...", category: "love", hint: "Forever", thumbnail: "https://picsum.photos/id/83/400/700", background: "#fef3c7", text: "Love you", subtext: "Forever", fontFamily: "'Great Vibes', cursive", ink: "#000000", layout: "collage-2", premium: false, tags: ['love', 'collage-2'] },
  { id: "fire-love-1083", name: "Love you ✨...", category: "love", hint: "Forever", thumbnail: "https://picsum.photos/id/84/400/700", background: "#e8d5c4", text: "Love you ✨", subtext: "Forever", fontFamily: "'Dancing Script', cursive", ink: "#ffffff", layout: "collage-4", premium: false, tags: ['love', 'collage-4'] },
  { id: "fire-love-1084", name: "Love you 💖...", category: "love", hint: "Forever", thumbnail: "https://picsum.photos/id/85/400/700", background: "#e8d5c4", text: "Love you 💖", subtext: "Forever", fontFamily: "'Dancing Script', cursive", ink: "#ffffff", layout: "scrapbook", premium: false, tags: ['love', 'scrapbook'] },
  { id: "fire-love-1085", name: "Love you 🎉...", category: "love", hint: "Forever", thumbnail: "https://picsum.photos/id/86/400/700", background: "#fff8e7", text: "Love you 🎉", subtext: "Forever", fontFamily: "'Playfair Display', serif", ink: "#000000", layout: "scrapbook", premium: false, tags: ['love', 'scrapbook'] },
  { id: "fire-minimal-1086", name: "Aesthetic ✨...", category: "minimal", hint: "Soft", thumbnail: "https://picsum.photos/id/87/400/700", background: "#fef3c7", text: "Aesthetic ✨", subtext: "Soft", fontFamily: "sans-serif", ink: "#000000", layout: "collage-2", premium: false, tags: ['minimal', 'collage-2'] },
  { id: "fire-minimal-1087", name: "Aesthetic 🎉...", category: "minimal", hint: "Soft", thumbnail: "https://picsum.photos/id/88/400/700", background: "#ffffff", text: "Aesthetic 🎉", subtext: "Soft", fontFamily: "sans-serif", ink: "#000000", layout: "polaroid", premium: false, tags: ['minimal', 'polaroid'] },
  { id: "fire-minimal-1088", name: "Minimal 💖...", category: "minimal", hint: "Clean", thumbnail: "https://picsum.photos/id/89/400/700", background: "#e8d5c4", text: "Minimal 💖", subtext: "Clean", fontFamily: "'Great Vibes', cursive", ink: "#ffffff", layout: "polaroid", premium: false, tags: ['minimal', 'polaroid'] },
  { id: "fire-minimal-1089", name: "Minimal...", category: "minimal", hint: "Clean", thumbnail: "https://picsum.photos/id/90/400/700", background: "#fef3c7", text: "Minimal", subtext: "Clean", fontFamily: "'Great Vibes', cursive", ink: "#000000", layout: "collage-2", premium: false, tags: ['minimal', 'collage-2'] },
  { id: "fire-minimal-1090", name: "Aesthetic 🎉...", category: "minimal", hint: "Soft", thumbnail: "https://picsum.photos/id/91/400/700", background: "#fffaf0", text: "Aesthetic 🎉", subtext: "Soft", fontFamily: "'Playfair Display', serif", ink: "#000000", layout: "magazine", premium: false, tags: ['minimal', 'magazine'] },
  { id: "fire-minimal-1091", name: "Aesthetic...", category: "minimal", hint: "Soft", thumbnail: "https://picsum.photos/id/92/400/700", background: "#fff8e7", text: "Aesthetic", subtext: "Soft", fontFamily: "'Great Vibes', cursive", ink: "#000000", layout: "scrapbook", premium: false, tags: ['minimal', 'scrapbook'] },
  { id: "fire-minimal-1092", name: "Aesthetic 🌿...", category: "minimal", hint: "Soft", thumbnail: "https://picsum.photos/id/93/400/700", background: "#f5f1e8", text: "Aesthetic 🌿", subtext: "Soft", fontFamily: "'Playfair Display', serif", ink: "#000000", layout: "scrapbook", premium: false, tags: ['minimal', 'scrapbook'] },
  { id: "fire-minimal-1093", name: "Aesthetic ✨...", category: "minimal", hint: "Soft", thumbnail: "https://picsum.photos/id/94/400/700", background: "#fff8e7", text: "Aesthetic ✨", subtext: "Soft", fontFamily: "'Great Vibes', cursive", ink: "#000000", layout: "collage-2", premium: false, tags: ['minimal', 'collage-2'] },
  { id: "fire-trending-1094", name: "Trending 💫...", category: "birthday", hint: "Now", thumbnail: "https://picsum.photos/id/95/400/700", background: "#ffffff", text: "Trending 💫", subtext: "Now", fontFamily: "'Great Vibes', cursive", ink: "#000000", layout: "scrapbook", premium: false, tags: ['trending', 'scrapbook'] },
  { id: "fire-trending-1095", name: "Trending 🌸...", category: "birthday", hint: "Now", thumbnail: "https://picsum.photos/id/96/400/700", background: "#e8d5c4", text: "Trending 🌸", subtext: "Now", fontFamily: "sans-serif", ink: "#ffffff", layout: "collage-2", premium: false, tags: ['trending', 'collage-2'] },
  { id: "fire-trending-1096", name: "Trending ✨...", category: "birthday", hint: "Now", thumbnail: "https://picsum.photos/id/97/400/700", background: "#e8d5c4", text: "Trending ✨", subtext: "Now", fontFamily: "'Great Vibes', cursive", ink: "#ffffff", layout: "scrapbook", premium: false, tags: ['trending', 'scrapbook'] },
  { id: "fire-trending-1097", name: "Trending 💖...", category: "birthday", hint: "Now", thumbnail: "https://picsum.photos/id/98/400/700", background: "#fff8e7", text: "Trending 💖", subtext: "Now", fontFamily: "'Playfair Display', serif", ink: "#000000", layout: "collage-2", premium: false, tags: ['trending', 'collage-2'] },
  { id: "fire-trending-1098", name: "Trending 💫...", category: "birthday", hint: "Now", thumbnail: "https://picsum.photos/id/99/400/700", background: "#e8d5c4", text: "Trending 💫", subtext: "Now", fontFamily: "'Playfair Display', serif", ink: "#ffffff", layout: "collage-2", premium: false, tags: ['trending', 'collage-2'] },
  { id: "fire-trending-1099", name: "Trending 💖...", category: "birthday", hint: "Now", thumbnail: "https://picsum.photos/id/100/400/700", background: "#f5f1e8", text: "Trending 💖", subtext: "Now", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "magazine", premium: false, tags: ['trending', 'magazine'] },
  { id: "fire-trending-1100", name: "Trending...", category: "festival", hint: "Now", thumbnail: "https://picsum.photos/id/101/400/700", background: "#ffffff", text: "Trending", subtext: "Now", fontFamily: "'Playfair Display', serif", ink: "#000000", layout: "collage-3", premium: false, tags: ['trending', 'collage-3'] },
  { id: "fire-trending-1101", name: "Trending ✨...", category: "festival", hint: "Now", thumbnail: "https://picsum.photos/id/102/400/700", background: "#ffffff", text: "Trending ✨", subtext: "Now", fontFamily: "'Dancing Script', cursive", ink: "#000000", layout: "collage-3", premium: false, tags: ['trending', 'collage-3'] },
];

export const CANVA_CATEGORIES: { id: CanvaCategory; label: string }[] = [
  { id: 'trending', label: 'Trending' },
  { id: 'birthday', label: 'Birthday' },
  { id: 'anniversary', label: 'Anniversary' },
  { id: 'festival', label: 'Festival' },
  { id: 'fashion', label: 'Fashion' },
  { id: 'nature', label: 'Nature' },
  { id: 'memories', label: 'Memories' },
  { id: 'love', label: 'Love' },
  { id: 'minimal', label: 'Minimal' },
];
