/**
 * Bloom Progression — achievements.
 *
 * Achievements are the *special* accomplishments, deliberately separate from
 * goals (active tasks) and ranks (cumulative progression). Each one has a
 * real condition resolved against Bloom's own records — no participation
 * awards, no invented statistics, no repeat-every-day noise.
 *
 * Rarity is used sparingly and only where it means something: `notable` for
 * the first real weeks, `rare` for months of work, `signature` for the things
 * almost nobody reaches.
 */

import type { AchievementDef } from "./types";

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: "ach-first-bloom",
    title: "First Bloom",
    condition: "Tick your very first habit.",
    earnedLine: "The first flower of the journey.",
    spec: { on: "firstTick" },
    target: 1,
    rarity: "notable",
    domain: "habits",
    tone: "var(--rose)",
    emblem: "first-bloom",
  },
  {
    id: "ach-seven-strong",
    title: "Seven Days Strong",
    condition: "Keep seven days in a row of habit consistency.",
    earnedLine: "A full week, one day at a time.",
    spec: { on: "habitRun" },
    target: 7,
    rarity: "notable",
    domain: "consistency",
    tone: "var(--amber)",
    emblem: "sprout",
  },
  {
    id: "ach-consistent-mind",
    title: "Consistent Mind",
    condition: "Log your mood on seven days.",
    earnedLine: "You keep checking in with yourself.",
    spec: { on: "moodDays", window: 400 },
    target: 7,
    rarity: "notable",
    domain: "mindfulness",
    tone: "var(--sky)",
    emblem: "budding",
  },
  {
    id: "ach-early-riser",
    title: "Early Riser",
    condition: "Log five mornings that started before 07:30.",
    earnedLine: "Quiet mornings, kept.",
    spec: { on: "earlyDays", before: "07:30", window: 60 },
    target: 5,
    rarity: "notable",
    domain: "sleep",
    tone: "var(--gold)",
    emblem: "bloom",
  },
  {
    id: "ach-quiet-focus",
    title: "Quiet Focus",
    condition: "Log ten study sessions.",
    earnedLine: "Attention, practised.",
    spec: { on: "studySessions", window: 400 },
    target: 10,
    rarity: "notable",
    domain: "study",
    tone: "var(--violet)",
    emblem: "budding",
  },
  {
    id: "ach-movement-milestone",
    title: "Movement Milestone",
    condition: "Complete twenty-five movement sessions.",
    earnedLine: "Movement became a habit, not an event.",
    spec: { on: "movementSessions", window: 400 },
    target: 25,
    rarity: "notable",
    domain: "fitness",
    tone: "var(--sage)",
    emblem: "sprout",
  },
  {
    id: "ach-deep-rest",
    title: "Deep Rest",
    condition: "Honour rest on seven days — sleep that met your own goal.",
    earnedLine: "You gave rest its place.",
    spec: { on: "recoveryDays", window: 400 },
    target: 7,
    rarity: "notable",
    domain: "recovery",
    tone: "var(--violet)",
    emblem: "bloom",
  },
  {
    id: "ach-hydration-habit",
    title: "Hydration Habit",
    condition: "Log hydration on fourteen days.",
    earnedLine: "A small habit, quietly held.",
    spec: { on: "trackerDays", tracker: "water", window: 400 },
    target: 14,
    rarity: "notable",
    domain: "hydration",
    tone: "var(--sky)",
    emblem: "sprout",
  },
  {
    id: "ach-balance-keeper",
    title: "Balance Keeper",
    condition: "Check in with Bloom on thirty different days.",
    earnedLine: "A life with room for all of it.",
    spec: { on: "balanceDays", window: 400 },
    target: 30,
    rarity: "rare",
    domain: "self-care",
    tone: "var(--sage)",
    emblem: "evergreen",
  },
  {
    id: "ach-night-keeper",
    title: "Night Keeper",
    condition: "Log sixty nights of sleep.",
    earnedLine: "Two months of nights, recorded.",
    spec: { on: "trackerDays", tracker: "sleep", window: 400 },
    target: 60,
    rarity: "rare",
    domain: "sleep",
    tone: "var(--violet)",
    emblem: "perennial",
  },
  {
    id: "ach-thirty-strong",
    title: "Thirty Days Strong",
    condition: "Keep thirty days in a row of habit consistency.",
    earnedLine: "A month of showing up.",
    spec: { on: "habitRun" },
    target: 30,
    rarity: "rare",
    domain: "consistency",
    tone: "var(--gold)",
    emblem: "flourish",
  },
  {
    id: "ach-reflection-ritual",
    title: "Reflection Ritual",
    condition: "Reflect on thirty days.",
    earnedLine: "A practice, not a mood.",
    spec: { on: "moodDays", window: 400 },
    target: 30,
    rarity: "rare",
    domain: "mindfulness",
    tone: "var(--rose)",
    emblem: "flourish",
  },
  {
    id: "ach-century",
    title: "Century",
    condition: "Keep one hundred days of habit consistency.",
    earnedLine: "One hundred ordinary days, made to count.",
    spec: { on: "habitDays", window: 400 },
    target: 100,
    rarity: "rare",
    domain: "consistency",
    tone: "var(--amber)",
    emblem: "keeper",
  },
  {
    id: "ach-in-bloom",
    title: "In Bloom",
    condition: "Reach the rank of In Bloom.",
    earnedLine: "You built this. It opened.",
    spec: { on: "rankTier", tier: 5 },
    target: 1,
    rarity: "rare",
    domain: "milestones",
    tone: "var(--gold)",
    emblem: "bloom",
  },
  {
    id: "ach-flourish",
    title: "Flourish",
    condition: "Reach the rank of Flourish.",
    earnedLine: "Not just keeping up — growing.",
    spec: { on: "rankTier", tier: 6 },
    target: 1,
    rarity: "rare",
    domain: "milestones",
    tone: "var(--gold)",
    emblem: "flourish",
  },
  {
    id: "ach-evergreen",
    title: "Evergreen",
    condition: "Reach the rank of Evergreen.",
    earnedLine: "Seasons changed. You stayed.",
    spec: { on: "rankTier", tier: 8 },
    target: 1,
    rarity: "signature",
    domain: "milestones",
    tone: "var(--sage)",
    emblem: "evergreen",
  },
  {
    id: "ach-ten-thousand",
    title: "Ten Thousand",
    condition: "Earn 10,000 Bloom Points.",
    earnedLine: "Five figures of real days.",
    spec: { on: "points", amount: 10_000 },
    target: 1,
    rarity: "signature",
    domain: "milestones",
    tone: "var(--violet)",
    emblem: "everbloom",
  },
  {
    id: "ach-bloomkeeper",
    title: "Bloomkeeper",
    condition: "Reach the rank of Bloomkeeper.",
    earnedLine: "You tend the whole garden now.",
    spec: { on: "rankTier", tier: 12 },
    target: 1,
    rarity: "signature",
    domain: "milestones",
    tone: "var(--gold)",
    emblem: "bloomkeeper",
  },
  {
    id: "ach-year-of-bloom",
    title: "Year of Bloom",
    condition: "Keep 365 days of habit consistency.",
    earnedLine: "A year, in full bloom.",
    spec: { on: "habitDays", window: 400 },
    target: 365,
    rarity: "signature",
    domain: "consistency",
    tone: "var(--gold)",
    emblem: "perennial",
  },
];

export const ACHIEVEMENT_BY_ID = new Map<string, AchievementDef>(
  ACHIEVEMENTS.map((a) => [a.id, a]),
);

/** Earned first (newest first), then closest to being earned. */
export function sortByEarned<
  T extends { def: AchievementDef; unlocked: boolean; achievedAt: string | null; ratio: number },
>(list: readonly T[]): T[] {
  return [...list].sort((a, b) => {
    if (a.unlocked !== b.unlocked) return a.unlocked ? -1 : 1;
    if (a.achievedAt && b.achievedAt) return a.achievedAt < b.achievedAt ? 1 : -1;
    return b.ratio - a.ratio;
  });
}
