/**
 * Bloom tours — every corner, no unavailable navs, with good/bad + efficiency tips.
 *
 * Rules:
 * - Only target elements that exist when the tour runs. Steps with `when` returning false are skipped.
 * - Never explain a nav that the user doesn't have (cycle off, signed-out extras).
 * - Each step has a real job: what it is, how to use it fast, what good looks like, what not to do.
 */

import type { TourDefinition } from "@/lib/tour/types";

function isDesktop(): boolean {
  if (typeof window === "undefined") return true;
  return window.matchMedia("(min-width: 1024px)").matches;
}

function hasEl(target: string): boolean {
  if (typeof document === "undefined") return false;
  return Boolean(document.querySelector(`[data-tour=\"${target}\"]`));
}

export const TOURS: Record<string, TourDefinition> = {
  global: {
    id: "global",
    label: "Bloom in 60 seconds",
    description: "Your map of Bloom — only what you actually have.",
    steps: [
      {
        id: "g-nav-today",
        target: "nav-today",
        placement: "right",
        title: "Today — your home base",
        body: "This is where your day lands. Greeting, score, and what's left to shape the day.",
        tip: "Open Bloom here first thing — 30 seconds to log mood + one habit sets the whole map.",
        good: "Check Today morning and evening.",
        bad: "Don't treat it like a feed to scroll — it's a mirror.",
      },
      {
        id: "g-nav-trackers",
        target: "nav-trackers",
        placement: "right",
        title: "Trackers — your body, honestly",
        body: "Sleep, water, movement, study, energy, screen. One day at a time, drawn as a compass and a route.",
        tip: "Log at night, not in real time. Two minutes before bed is 90% accurate and 10x more sustainable.",
        good: "Log imperfectly — 6h sleep guessed beats 0h logged.",
        bad: "Don't chase perfect numbers. Bloom shows patterns, not grades.",
      },
      {
        id: "g-nav-mood",
        target: "nav-mood",
        placement: "right",
        title: "Mood — the intelligence",
        body: "Not a diary. Mood Intelligence shows stability, momentum, and what actually moves your mood.",
        tip: "Add one emotion + one line. The one-line note is what makes correlations real later.",
        good: "Name 1-2 emotions, not 5.",
        bad: "Don't only log when you're low — calm days teach the most.",
      },
      {
        id: "g-nav-cycle",
        target: "nav-cycle",
        placement: "right",
        title: "Cycle — if it's part of your Bloom",
        body: "Phases, predictions, and what today explains. You can turn it off in Profile → Personalization.",
        tip: "Log period days only — Bloom predicts the rest. No need to log every symptom daily.",
        good: "Log start/end of period consistently.",
        bad: "Don't log symptoms you didn't feel just to fill the day.",
        when: () => hasEl("nav-cycle"),
      },
      {
        id: "g-nav-rewards",
        target: "nav-rewards",
        placement: "right",
        title: "Rewards — quiet progress",
        body: "Rank, crest, and small things you earn by showing up. Not gamification — a record of care.",
        tip: "Check Rewards weekly, not daily. It's a slow burn.",
        good: "Equip one wallpaper or frame you like — it makes Today yours.",
        bad: "Don't grind. Points come from real logs, not taps.",
      },
      {
        id: "g-nav-coach",
        target: "nav-coach",
        placement: "right",
        title: "Coach — a second mind",
        body: "Ask, reflect, plan. Coach reads your actual record (mood, habits, cycle) to give context-aware answers.",
        tip: "Start with 'What should I focus on today?' — it's wired to your open tasks.",
        good: "Ask about patterns: 'Why am I low energy after 3pm?'",
        bad: "Don't treat it like search. It knows your data, not the internet.",
      },
      {
        id: "g-nav-profile",
        target: "nav-profile",
        placement: "right",
        title: "Profile — your space",
        body: "Identity, stories (24h), highlights, featured moment, privacy, and all your data controls.",
        tip: "Pick a @username early — it becomes your shareable address at /@handle.",
        good: "Keep profile private until you have 2-3 public moments you're proud of.",
        bad: "Don't share private stories by accident — check visibility before publishing.",
      },
    ],
  },

  home: {
    id: "home",
    label: "Today — make it yours",
    description: "The day, decoded.",
    steps: [
      {
        id: "h-greeting",
        target: "home-greeting",
        placement: "bottom",
        title: "Greeting that knows you",
        body: "Bloom says good morning with your name and how many things are left to shape the day. It's not fluff — it's derived from habits + mood + trackers.",
        tip: "If it says 'One thing left', do that one thing now. That's the whole system.",
        good: "Read the subline — 'Day one' vs 'Everything logged' changes your intention.",
        bad: "Don't ignore it when it says 0 left. Enjoy the quiet — that's the goal.",
      },
      {
        id: "h-mood-chip",
        target: "home-chip-mood",
        placement: "bottom",
        title: "Log mood in 10 seconds",
        body: "Tap to open the composer. Mood, emotions, energy, stress — and an optional note that makes future insights real.",
        tip: "Use the 'usual' markers — Bloom shows your typical time and mood to keep you honest.",
        good: "Log same time daily (e.g., after dinner).",
        bad: "Don't wait for a perfect moment to log. A quick 6/10 is better than no entry.",
      },
      {
        id: "h-metrics-chip",
        target: "home-chip-metrics",
        placement: "bottom",
        title: "Log body metrics at night",
        body: "Sleep, water, movement, screen — 6 sliders. Bloom computes goals met and how today connects.",
        tip: "Do it while brushing teeth. 60 seconds, same spot, builds the habit.",
        good: "Estimate. Bloom is about trends, not lab accuracy.",
        bad: "Don't log 5 times a day. Once at night is enough.",
      },
      {
        id: "h-stories",
        target: "home-stories",
        placement: "bottom",
        title: "Stories — 24 hours, then kept",
        body: "Your day in moments. Tap your avatar to add, tap others to view. Unseen rings glow with your accent.",
        tip: "Add 1 story after logging mood — it becomes your visual diary without extra work.",
        good: "Share public moments that feel like you.",
        bad: "Don't over-share. 1-2 a day keeps the ring meaningful.",
      },
      {
        id: "h-habits",
        target: "home-habits",
        placement: "top",
        title: "Habits — today only",
        body: "What you said matters. Toggle to complete. Long-press or menu to edit, pause, archive.",
        tip: "Pause, don't delete, when life happens. Paused habits keep history and come back.",
        good: "Keep 3-5 daily habits. More than 7 burns out.",
        bad: "Don't create a habit for everything. If you won't do it 4x/week, it's a task, not a habit.",
      },
      {
        id: "h-progress",
        target: "home-progress",
        placement: "right",
        title: "Progress score — not a grade",
        body: "A 0-100 from trackers + habits + mood. It's a nudge, not a judgment. 70 is a great day.",
        tip: "Tap to log missing metrics — it's a shortcut.",
        good: "Watch 7-day trend, not today's number.",
        bad: "Don't chase 100. Consistency beats peaks.",
      },
      {
        id: "h-map",
        target: "home-map",
        placement: "left",
        title: "Connection map — how things link",
        body: "Nodes are your signals (sleep, mood, habits, cycle). Arcs appear when two signals share enough days to correlate.",
        tip: "No arcs yet? Log 7 days of mood + sleep. That's the minimum for a real link.",
        good: "Follow an arc: 'sleep → mood' often explains low days.",
        bad: "Don't read causation. It's correlation — a clue, not a diagnosis.",
      },
      {
        id: "h-flow",
        target: "home-flow",
        placement: "top",
        title: "Flow — when to do what",
        body: "Your day ordered by energy. Morning peak, afternoon dip, evening wind-down — based on your actual logs.",
        tip: "Drag habits to your peak hours in Trackers → Atlas. Flow respects that.",
        good: "Do hard habits in flow's green hours.",
        bad: "Don't fight your flow. If 3pm is always low, don't schedule deep work there.",
      },
      {
        id: "h-phase",
        target: "home-phase",
        placement: "left",
        title: "Cycle phase — if you track it",
        body: "What phase you're in and what it tends to mean. Data-driven, not horoscope.",
        tip: "Tap to go to Cycle — predictions live there.",
        good: "Use it to plan, not to excuse. 'Luteal → lower energy' is info, not fate.",
        bad: "Don't log symptoms to match the phase. Log what you felt.",
        when: () => hasEl("home-phase"),
      },
      {
        id: "h-fab",
        target: "home-fab",
        placement: "top",
        title: "Add habit — always in reach",
        body: "Floating button, thumb zone. Creates a habit with name, icon, color, schedule.",
        tip: "Name it like a verb: 'Walk 10m', not 'Health'. Verbs get done.",
        good: "Start with 2 habits: one body, one mind.",
        bad: "Don't add 5 at once. Add one, do it 3 days, then add next.",
        when: () => !isDesktop(),
      },
    ],
  },

  mood: {
    id: "mood",
    label: "Mood — understand how you feel",
    description: "Discover why, not just what.",
    steps: [
      {
        id: "m-compose",
        target: "mood-compose",
        placement: "bottom",
        title: "Compose — your check-in",
        body: "Mood score, emotions, energy, stress, sleep quality, plus note. The note is optional but powerful.",
        tip: "One emotion + one sentence beats a paragraph once a week. Consistency creates insights.",
        good: "Write what happened, not just how you feel: 'Slept 5h, meeting ran late'.",
        bad: "Don't rate 10 or 1 every day. Use the middle — 5-8 is where patterns live.",
      },
      {
        id: "m-timeline",
        target: "mood-timeline",
        placement: "top",
        title: "Timeline — your journey",
        body: "Every entry, beautiful and searchable. Tap to edit, share as story, or delete.",
        tip: "Tap a day to see what else you logged that day — sleep, habits, cycle.",
        good: "Review last 7 days on Sunday. 2 minutes.",
        bad: "Don't delete low days. They teach your correlations.",
      },
      {
        id: "m-insights",
        target: "mood-insights",
        placement: "top",
        title: "Insights — auto-generated",
        body: "Bloom reads your entries and says: 'You feel calmer after walks' — only when data supports it.",
        tip: "Need more insights? Log 14 days with notes. That's the threshold.",
        good: "Act on one insight per week.",
        bad: "Don't treat insights as orders. They're mirrors.",
      },
      {
        id: "m-distribution",
        target: "mood-distribution",
        placement: "top",
        title: "Distribution — your range",
        body: "How often you feel each way. A wide range is human. A narrow high range is stability.",
        tip: "If 80% is 4-6, try one energizing habit for a week and watch distribution shift.",
        good: "Aim for stability, not constant happiness.",
        bad: "Don't compare to others. This is your baseline.",
      },
    ],
  },

  trackers: {
    id: "trackers",
    label: "Trackers — the honest log",
    description: "Six signals, one day at a time.",
    steps: [
      {
        id: "t-compass",
        target: "trackers-compass",
        placement: "bottom",
        title: "Compass — 24 hour view",
        body: "Sleep as night arc, others as rings revealed by % of target. Tap a segment to log that tracker.",
        tip: "Tap the ring, not the label — it's the fastest log entry in the app.",
        good: "Set realistic targets in settings — 7h sleep, 2L water, 30m movement.",
        bad: "Don't set targets you never hit. Lower them — consistency matters more.",
      },
      {
        id: "t-ledger",
        target: "trackers-ledger",
        placement: "top",
        title: "Ledger — last 14 days",
        body: "A route through your last two weeks. Gaps are okay — they show life, not failure.",
        tip: "A straight line of gaps? That's a sign to pause a tracker, not to feel bad.",
        good: "Look for streaks of 3+ days — that's a habit forming.",
        bad: "Don't fill gaps from memory 5 days later. Leave them.",
      },
      {
        id: "t-goals",
        target: "trackers-goals",
        placement: "top",
        title: "Goals — met today",
        body: "How many of 6 goals you hit today. 3/6 is solid. 6/6 is a great day.",
        tip: "Goals met → points → rank. It's all connected.",
        good: "Celebrate 4/6. That's above average.",
        bad: "Don't edit yesterday to make today look better.",
      },
    ],
  },

  cycle: {
    id: "cycle",
    label: "Cycle — your rhythm",
    description: "Predict, not prescribe.",
    steps: [
      {
        id: "c-calendar",
        target: "cycle-calendar",
        placement: "bottom",
        title: "Calendar — the real record",
        body: "Period days, predicted days, fertile window. Tap a day to log. Long history = better predictions.",
        tip: "Only log period start/end at first. Add symptoms later if you want — predictions don't need them.",
        good: "Log within 2 days. Late logs hurt accuracy less than missing logs.",
        bad: "Don't log spotting as period unless it is. It confuses the model.",
      },
      {
        id: "c-predictions",
        target: "cycle-predictions",
        placement: "top",
        title: "Predictions — how sure?",
        body: "Bloom shows confidence. 3 cycles = okay, 6 cycles = good, 12 = great.",
        tip: "Import past periods in Profile → Settings → Import to jumpstart accuracy.",
        good: "Check predictions at start of month to plan.",
        bad: "Don't treat predictions as guarantees. Bodies vary.",
      },
      {
        id: "c-insights",
        target: "cycle-insights",
        placement: "top",
        title: "Phase insights — what phase explains",
        body: "Energy, mood, focus tendencies per phase — from science, not astrology, and filtered by your logs.",
        tip: "Use 'Ease before period' toggle if you want Bloom to be gentler in luteal.",
        good: "Read phase as context, not excuse.",
        bad: "Don't over-log symptoms to match expected phase.",
      },
    ],
  },

  coach: {
    id: "coach",
    label: "Coach — ask, reflect, plan",
    description: "A second mind that knows your data.",
    steps: [
      {
        id: "co-lenses",
        target: "coach-lenses",
        placement: "right",
        title: "Lenses — Ask, Reflect, Plan",
        body: "Ask = answers, Reflect = patterns, Plan = actions. Same coach, different intention.",
        tip: "Use Reflect on Sunday: 'What worked this week?' — it reads your actual logs.",
        good: "Pick lens before typing — it changes how coach replies.",
        bad: "Don't stay in Ask for everything. Reflect finds patterns Ask won't.",
      },
      {
        id: "co-composer",
        target: "coach-composer",
        placement: "top",
        title: "Composer — talk like a human",
        body: "Type, attach a photo, or use voice. Coach sees your Today, mood, habits, cycle — not the internet.",
        tip: "Try: 'Why am I tired at 3pm?' or 'Help me plan tomorrow around my cycle'.",
        good: "Mention real data: 'I slept 5h, should I walk?'",
        bad: "Don't ask for medical diagnosis. Coach is a companion, not a doctor.",
      },
      {
        id: "co-quick",
        target: "coach-quick",
        placement: "top",
        title: "Quick palette — start fast",
        body: "One-tap starters based on your day. Morning vs evening changes them.",
        tip: "These are personalized — if you see 'Plan around luteal', tap it. It's timely.",
        good: "Use quick actions when you don't know what to ask.",
        bad: "Don't ignore context panel — it shows what coach is reading.",
      },
      {
        id: "co-context",
        target: "coach-context",
        placement: "left",
        title: "Context — what coach sees",
        body: "Exactly what data coach is using right now. Nothing hidden. You can clear it.",
        tip: "Clear context if you want a fresh take without history.",
        good: "Check context when answer feels off — maybe it's reading old data.",
        bad: "Don't share sensitive things you don't want in context.",
      },
    ],
  },

  profile: {
    id: "profile",
    label: "Profile — your space, your rules",
    description: "Identity, moments, and control.",
    steps: [
      {
        id: "p-avatar",
        target: "profile-avatar",
        placement: "bottom",
        title: "Avatar — your story ring",
        body: "Glows when you have unseen stories. Tap to view stories, tap + to add one. Ring color = your accent.",
        tip: "Add a story right after editing profile — it makes your space feel alive.",
        good: "Use a real photo or preset — initials are okay but photo builds trust if you share.",
        bad: "Don't leave default name 'Bloom User' if you share publicly.",
      },
      {
        id: "p-share",
        target: "profile-share",
        placement: "left",
        title: "Share profile — new Bloom sheet",
        body: "Opens the unified share sheet: preview, link, copy, system share, privacy note. Same from hero and settings.",
        tip: "Share only after you set @username and have 1 featured moment. First impression matters.",
        good: "Preview as others see it before sharing link anywhere.",
        bad: "Don't share when profile is private — visitors see 'private' note and bounce.",
      },
      {
        id: "p-edit",
        target: "profile-edit",
        placement: "bottom",
        title: "Edit profile — name, handle, bio, accent",
        body: "Display name, @username (your address), bio, accent color. @username change breaks old links.",
        tip: "Bio: one line about what you track and why. 'Tracking sleep + mood to understand energy'.",
        good: "Pick accent that feels like you — it tints your whole profile.",
        bad: "Don't use @username with spaces or caps — keep it simple, lowercase.",
      },
      {
        id: "p-record",
        target: "profile-record",
        placement: "top",
        title: "Record — last 12 weeks",
        body: "A GitHub-style grid of logged days. Darker = more logged. Tap a day to jump to that day's page.",
        tip: "Tap a dark cell — it takes you to mood/trackers/cycle for that date. Fast time travel.",
        good: "Aim for 4-5 dark days per week, not 7. Rest is part of record too.",
        bad: "Don't obsess over gaps. 12 weeks shows pattern, not perfection.",
      },
      {
        id: "p-featured",
        target: "profile-featured",
        placement: "top",
        title: "Featured moment — your pinned post",
        body: "One story, reflection, reward, or milestone that feels like you. Only one — curation is care.",
        tip: "Pin a milestone or reflection, not a random photo. It should explain you in 10 seconds.",
        good: "Change it monthly — what represents you evolves.",
        bad: "Don't leave it empty if you share publicly. Empty pinned feels unfinished.",
      },
      {
        id: "p-tabs",
        target: "profile-tabs",
        placement: "bottom",
        title: "Moments / Highlights / Journey",
        body: "Moments = 24h stories. Highlights = kept circles. Journey = milestones + stats.",
        tip: "Highlights are your portfolio — group stories by theme: 'Morning walks', 'Reflections'.",
        good: "Create 2-3 highlights max. More than 5 feels cluttered.",
        bad: "Don't put every story in highlights. Keep highlights curated.",
      },
      {
        id: "p-privacy",
        target: "profile-privacy",
        placement: "left",
        title: "Privacy — you own the switch",
        body: "Profile visibility public/private, story default visibility, who sees what. Private by default.",
        tip: "Set profile public but stories private — you control per story what is shared.",
        good: "Review privacy after first week of sharing.",
        bad: "Don't make everything public on day one. Start private, then open gradually.",
      },
      {
        id: "p-data",
        target: "profile-data",
        placement: "top",
        title: "Data — download, reminders, erase",
        body: "Download everything (JSON, built on device), reminders (with test), install prompt, erase everything (typed confirmation).",
        tip: "Download everything before erase — it's your backup and works offline.",
        good: "Set one evening reminder, not five. One nudge is enough.",
        bad: "Don't set reminders for habits you don't have a time for — they won't fire.",
      },
    ],
  },

  rewards: {
    id: "rewards",
    label: "Rewards — quiet progress",
    description: "Not gamification. A record.",
    steps: [
      {
        id: "r-rank",
        target: "rewards-rank",
        placement: "bottom",
        title: "Rank — where you are",
        body: "From Seed to Bloom, based on points from real logs. No cheating — points only from actions.",
        tip: "Check rank weekly. Daily rank checking makes it feel like a game — it's not.",
        good: "Rank up by logging consistently, not by logging more per day.",
        bad: "Don't chase rank by fake logs. It defeats the purpose.",
      },
      {
        id: "r-atelier",
        target: "rewards-atelier",
        placement: "top",
        title: "Atelier — make it yours",
        body: "Wallpapers, frames, accents, emblems. Equip one — it shows up in Today hero, avatar, etc.",
        tip: "Equip wallpaper + frame from same palette — it feels intentional.",
        good: "Pick one wallpaper you love for a month. Let it become your Bloom.",
        bad: "Don't equip everything you unlock. Curation > collection.",
      },
      {
        id: "r-goals",
        target: "rewards-goals",
        placement: "top",
        title: "Goals — what's next",
        body: "Milestones tied to real behavior: 7-day streak, 30 mood entries, etc. Tap to share as story.",
        tip: "Share a goal when you hit it — it becomes a story and a memory.",
        good: "Focus on next 2 goals, not all 20.",
        bad: "Don't share goals you haven't earned — Bloom only lets you share real achievements.",
      },
    ],
  },
};

export function getTour(id: string): TourDefinition | null {
  return TOURS[id] ?? null;
}

export function getVisibleSteps(def: TourDefinition): TourDefinition["steps"] {
  return def.steps.filter((s) => {
    if (s.when && !s.when()) return false;
    if (typeof document !== "undefined" && !document.querySelector(`[data-tour=\"${s.target}\"]`)) {
      // still allow if target might appear after mount — keep it, but overlay will skip if not found
      return true;
    }
    return true;
  });
}
