#!/usr/bin/env python3
"""Assemble every migration into one file you can paste into the SQL editor.

    python3 scripts/make-sql.py

Writes supabase/COMPLETE-SETUP.sql. The order below is the dependency order,
not alphabetically — the identity migration ALTERs public.profiles, so the
bootstrap has to come first. Every migration is written with `if not exists` /
`create or replace`, so running the combined file twice is harmless.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIGRATIONS = ROOT / "supabase" / "migrations"
OUT = ROOT / "supabase" / "COMPLETE-SETUP.sql"

# filename → one line on what it gives you
ORDER: list[tuple[str, str]] = [
    ("20260826_reward_delivery.sql", "reward_items, reward_assignments, app_admins + the reward functions"),
    ("20260827_profiles_bootstrap.sql", "public.profiles — created only if your project doesn't have it yet"),
    ("20260828_profile_identity_stories.sql", "identity columns, privacy, stories, highlights, the profile-media bucket"),
    ("20260829_cycle_intelligence.sql", "cycle_entries — the cycle page"),
    ("20260830120000_tracker_days.sql", "tracker_days — the trackers page"),
    ("20260831000000_mood_entries.sql", "mood_entries — the mood page"),
    ("20260831000100_coach_memory.sql", "coach_messages, coach_memory — the coach's thread and facts"),
]

HEADER = """-- ===========================================================================
-- Bloom — complete Supabase setup
--
-- Paste this whole file into your project's SQL editor and run it once.
-- Generated by scripts/make-sql.py — edit a migration, re-run the script.
--
-- It is safe to run on a project that already has some of these tables: every
-- statement is `create ... if not exists` / `create or replace` / `drop ... if
-- exists`, so re-running changes nothing that is already correct.
--
-- What this gives you:
{table_list}
-- Then put these in .env.local and restart the dev server:
--
--   VITE_SUPABASE_URL=https://<your-project>.supabase.co
--   VITE_SUPABASE_ANON_KEY=<your anon key>
--
-- Full write-up: docs/SUPABASE-SETUP.md
-- ===========================================================================
"""


def main() -> None:
    missing = [name for name, _ in ORDER if not (MIGRATIONS / name).is_file()]
    if missing:
        raise SystemExit(f"missing migrations: {missing}")
    extra = sorted(p.name for p in MIGRATIONS.glob("*.sql") if p.name not in dict(ORDER))
    if extra:
        raise SystemExit(f"migrations not listed in ORDER: {extra}")

    parts = [HEADER.format(table_list="".join(f"--   • {what}\n" for _, what in ORDER))]
    for name, what in ORDER:
        body = (MIGRATIONS / name).read_text().strip()
        parts.append(
            f"\n\n-- ---------------------------------------------------------------------------\n"
            f"-- {name}\n"
            f"-- {what}\n"
            f"-- ---------------------------------------------------------------------------\n\n"
            f"{body}\n"
        )
    OUT.write_text("".join(parts))
    lines = OUT.read_text().count("\n")
    print(f"{OUT.relative_to(ROOT)}: {len(ORDER)} migrations, {lines} lines, {OUT.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
