/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CycleRouteImport } from './routes/cycle'
import { Route as CycleClassicRouteImport } from './routes/cycle-classic'
import { Route as CycleStylesRouteImport } from './routes/cycle-styles'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as TrackersRouteImport } from './routes/trackers'
import { Route as AdminRewardsRouteImport } from './routes/admin/rewards'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleRoute = CycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleClassicRoute = CycleClassicRouteImport.update({
  id: '/cycle-classic',
  path: '/cycle-classic',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleStylesRoute = CycleStylesRouteImport.update({
  id: '/cycle-styles',
  path: '/cycle-styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersRoute = TrackersRouteImport.update({
  id: '/trackers',
  path: '/trackers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/admin/rewards',
  path: '/admin/rewards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/coach': typeof CoachRoute
  '/cycle': typeof CycleRoute
  '/cycle-classic': typeof CycleClassicRoute
  '/cycle-styles': typeof CycleStylesRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/trackers': typeof TrackersRoute
  '/admin/rewards': typeof AdminRewardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/coach': typeof CoachRoute
  '/cycle': typeof CycleRoute
  '/cycle-classic': typeof CycleClassicRoute
  '/cycle-styles': typeof CycleStylesRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/trackers': typeof TrackersRoute
  '/admin/rewards': typeof AdminRewardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/coach': typeof CoachRoute
  '/cycle': typeof CycleRoute
  '/cycle-classic': typeof CycleClassicRoute
  '/cycle-styles': typeof CycleStylesRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/trackers': typeof TrackersRoute
  '/admin/rewards': typeof AdminRewardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/coach'
    | '/cycle'
    | '/cycle-classic'
    | '/cycle-styles'
    | '/profile'
    | '/rewards'
    | '/trackers'
    | '/admin/rewards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$handle'
    | '/coach'
    | '/cycle'
    | '/cycle-classic'
    | '/cycle-styles'
    | '/profile'
    | '/rewards'
    | '/trackers'
    | '/admin/rewards'
  id:
    | '__root__'
    | '/'
    | '/$handle'
    | '/coach'
    | '/cycle'
    | '/cycle-classic'
    | '/cycle-styles'
    | '/profile'
    | '/rewards'
    | '/trackers'
    | '/admin/rewards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleRoute: typeof HandleRoute
  CoachRoute: typeof CoachRoute
  CycleRoute: typeof CycleRoute
  CycleClassicRoute: typeof CycleClassicRoute
  CycleStylesRoute: typeof CycleStylesRoute
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  TrackersRoute: typeof TrackersRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle': {
      id: '/cycle'
      path: '/cycle'
      fullPath: '/cycle'
      preLoaderRoute: typeof CycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle-classic': {
      id: '/cycle-classic'
      path: '/cycle-classic'
      fullPath: '/cycle-classic'
      preLoaderRoute: typeof CycleClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle-styles': {
      id: '/cycle-styles'
      path: '/cycle-styles'
      fullPath: '/cycle-styles'
      preLoaderRoute: typeof CycleStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers': {
      id: '/trackers'
      path: '/trackers'
      fullPath: '/trackers'
      preLoaderRoute: typeof TrackersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/admin/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleRoute: HandleRoute,
  CoachRoute: CoachRoute,
  CycleRoute: CycleRoute,
  CycleClassicRoute: CycleClassicRoute,
  CycleStylesRoute: CycleStylesRoute,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  TrackersRoute: TrackersRoute,
  AdminRewardsRoute: AdminRewardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
